### ISSUE TITLE
Number of Reading list

### ISSUE THREAD

**Issue by thomasbnt** [thepracticaldev/dev.to#9040] opened 2020-06-30 21:15 UTC
**Is your feature request related to a problem? Please describe.**

I have __19 posts to read for later__, but at the main page it show 89. 

#### Why is that? 
That's the total number of posts to read later (active read later posts + archived posts). **Even though I've archived them**, the number keeps increasing. :disappointed: 

#### Why is that a problem? 
Two points, 

- It's not clear how many posts we set aside to read later...
- The larger the number, the more complicated it will be to adjust it to the design. 

|![image](https://user-images.githubusercontent.com/14293805/86177074-4a6c8a00-bb26-11ea-8521-b5c5e58ed8fc.png) | ![image](https://user-images.githubusercontent.com/14293805/86176916-07121b80-bb26-11ea-8165-eeb5024f0f88.png) |
|-|-|

**Describe the solution you'd like**

Just the total of read posts for later and no archives posts.

**Describe alternatives you've considered**

Beautiful panel like `/mod` or `/dashboard` with total number of **Archive posts(*A*)**, **reading list (*R*)** and ***A + R***.

**Comment by jacobherrington** [comment] 2020-06-30 21:42
This is possibly a duplicate of https://github.com/thepracticaldev/dev.to/issues/8164!

**Comment by jacobherrington** [comment] 2020-06-30 21:44
I'm going to go ahead and close this as a duplicate, if you'd like to voice your opinion in #8164, that would be great! I agree that we should look into solving this bug!

**Closed by jacobherrington** 2020-06-30 21:44 UTC
Labels: area: reading list, type: bug

**Comment by thomasbnt** [comment] 2020-07-01 05:28
Thanks @jacobherrington 😉☕
