### ISSUE TITLE
Article links in DEV Digest emails not opening correctly.

### ISSUE THREAD

**Issue by manan30** [thepracticaldev/dev.to#7993] opened 2020-05-20 22:36 UTC
**Describe the bug**
Whenever I click on the article links provided inside the DEV Digest email, it always opens the main feed rather than the article itself.

**To Reproduce**
Click on any article links in the DEV Digest emails and you'll be taken to the feed rather than the article. Eg. Click [this](https://dev.to/ahoy/messages/TgplUcptixPi35Ook4bZeIbnSCe6D0Pc/click?signature=29b7132679695e624b24bb7fd71afd5490614174&url=https%3A%2F%2Fdev.to%2Ffayazara%2Fthis-free-tools-for-developers-are-45p3%3Futm_source%3Ddigest_mailer%26utm_medium%3Demail%26utm_campaign%3Ddigest_email) link and you'll see it takes you to the home feed.

**Comment by rhymes** [comment] 2020-05-21 09:32
Thanks @manan30, I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/7982 and let you know we're investigating

**Closed by rhymes** 2020-05-21 09:32 UTC
Labels: triage
