### ISSUE TITLE
Allow hyphen `-` in article tags

### ISSUE THREAD

**Issue by ahmedash95** [thepracticaldev/dev.to#6057] opened 2020-02-13 13:32 UTC
Hello Folks,

One of the problems I've found in dev.to and I wish to get it solved, that It's really hard to write tags with alphaNumeric validations only. there is no way to write eg: design-patterns, dependency-injection, etc..
![image](https://user-images.githubusercontent.com/8272048/74439840-3c66e700-4e6d-11ea-845e-d8a5b3e6cc53.png)

a good solution is to support at least hyphen so it's easy for the community to pick and write tags

**Comment by rhymes** [comment] 2020-02-13 14:39
Hi @ahmedash95 thanks for your report!

I think this is a known issues and if you don't mind I'm going to close it as a duplicate of https://github.com/thepracticaldev/dev.to/issues/2347 

It'd be great if you could add to the discussion there.

Thanks again!

**Closed by rhymes** 2020-02-13 14:39 UTC
Labels: triage
