### ISSUE TITLE
Bug in footer

### ISSUE THREAD

**Issue by sa-js** [thepracticaldev/dev.to#3945] opened 2019-09-05 05:27 UTC
**Describe the bug**
UI issue in footer

**Steps To Reproduce**
1. Go to Dashboard
2. You will see a list of posts
3. Click on any of your posts
4. Press browser back button
5. You can see that footer on dashboard is not aligned with list of posts

**Expected behavior**
Footer should be aligned with posts list

**Screenshots**
![Screen Shot 2019-09-05 at 10 21 34 AM](https://user-images.githubusercontent.com/17095740/64314054-12a8ba80-cfc7-11e9-93c3-e041050c7b4a.png)

**Desktop (please complete the following information):**

- OS: Mac OS High Sierra
- Browser: Chrome
- Version: 76.0.3809.132

**Comment by lucianolima00** [comment] 2019-09-05 20:20
Hey @sa-js, I'd like to do this issue

**Comment by lynnewritescode** [comment] 2019-09-25 21:52
I'm not sure the associated PR will fix this. The issue is that it's not getting the 'centered-footer' class when you click back in the browser - so the style fix applied won't work.

**Comment by rubynho** [comment] 2019-09-27 17:58
Can I work on this issue, @jessleenyc?

**Comment by maestromac** [comment] 2019-10-02 17:39
Resolved with https://github.com/thepracticaldev/dev.to/pull/3965

**Closed by maestromac** 2019-10-02 17:39 UTC
Labels: good first issue, help wanted, tech: html/css
