### ISSUE TITLE
Filter my RSS feed by tag

### ISSUE THREAD

**Issue by nverinaud** [thepracticaldev/dev.to#1916] opened 2019-02-27 10:43 UTC
**Feature Request**
I would like to be able to retrieve my posts filtered by some tags in order to give the possibility to someone else to follow my posts but only for the area of interests she cares about.

**Proposal**
It would be great to reach `https://dev.to/feed/{username}?tags=productivity,ios` and have an RSS feed of `{username}`'s posts filtered by a coma-separated list of tags.

**Alternatives**
I do not know of any service able to filter some RSS feeds, but would be happy to use one !

**Additional context**
I would like to give Dave Verwer (iOS Dev Weekly Newsletter author) access to posts I publish on Dev.to but only about iOS. He asked me to contribute by going here : https://iosdevdirectory.com/contributing/

**Comment by maestromac** [comment] 2019-02-27 16:22
Thank you for this issue @nverinaud . There already an issue on this. Please continue the conversation there.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/201

**Closed by maestromac** 2019-02-27 16:22 UTC
