### ISSUE TITLE
Github Liquid tag header rendering alignment is a bit off in a notification

### ISSUE THREAD

**Issue by rhymes** [thepracticaldev/dev.to#3661] opened 2019-08-08 16:16 UTC
**Describe the bug**

I just noticed that if a comment notification contains a GitHub Liquid tag, its header alignment is a bit off.

I think it has something to do with how the tag `ltag_github-liquid-tag h1` is positioned 

**To Reproduce**

This might be a little hard to reproduce in development. You'd need a second user, you'd need to create a comment that gets notified to the first user, containing a GitHub liquid tag

**Expected behavior**

Expect the header of the liquid tag to be inside the border of the notification

**Screenshots**

![Screen Shot 2019-08-08 at 18 05 20](https://user-images.githubusercontent.com/146201/62719508-7364c780-ba08-11e9-8be3-651f8407fbd7.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Firefox
- Version: 69.0b11

**Comment by zerefwayne** [comment] 2019-08-09 07:06
@jessleenyc I would like to take up this issue.

**Comment by jessleenyc** [comment] 2019-08-09 18:20
@zerefwayne Great! Just a heads up that you'll want to run jobs `rake jobs:work` for notifications to show up when actions are taken. Or, you could generate them from the rails console and run the class methods from `notification.rb`.

**Comment by artoodeeto** [comment] 2019-10-06 15:21
@jessleenyc noob question. is this open or closed? it has hactoberfest labeled but theres a close above it. If still opencan I take this? @zerefwayne you still working on this bro?

**Comment by rhymes** [comment] 2019-10-06 16:04
hi @artoodeeto, this issue is still open, you can see the status at the top near the description. the "closed" you see here above is from a referenced issue, not this one

If you want to take a look at how to generate notifications, you can check: https://docs.dev.to/backend/notification/

let us know if you need help!

**Comment by artoodeeto** [comment] 2019-10-06 16:22
@rhymes ohh silly me. Thought this was closed and just marked as hactoberfest. Anyway I created 2 accounts already. I created new post with a `github` tag and comment back and forth but couldn't reproduced this bug. I'm using firefox(dev edition), chrome, and safari. no luck.

**Comment by rhymes** [comment] 2019-10-06 16:25
@artoodeeto it could be that this got fixed by itself, after all the bug is from August :)

If you can confirm with a screenshot, I think we could go ahead and close this issue

**Comment by artoodeeto** [comment] 2019-10-06 16:30
@rhymes I think im doing it wrong. hold on. let me try to do it again.

**Comment by artoodeeto** [comment] 2019-10-06 16:37
![Screen Shot 2019-10-06 at 9 36 57 AM](https://user-images.githubusercontent.com/19770382/66272307-e62dcb80-e81c-11e9-8b44-ee896304ab4d.png)

**Comment by artoodeeto** [comment] 2019-10-06 16:38
@rhymes  still here. let me fix this. after I comeback home. thank you sir, appreciate the help. :)

**Closed** 2019-10-08 17:43 UTC
Labels: area: notifications, good first issue, hacktoberfest, tech: html/css, type: bug
