### ISSUE TITLE
Duplicate RSS entries on https://dev.to/feed

### ISSUE THREAD

**Issue by IvanDelsinne** [thepracticaldev/dev.to#1758] opened 2019-02-07 12:28 UTC
I'm using Miniflux as a RSS reader to get the dev.to latest articles, and I just noticed that it now duplicates almost every entry.

**Screenshots**

![](https://pix.watch/RN91DL/zp1X9f.jpeg)

I'm using the following URL as RSS feed source: `https://dev.to/feed`.

**Comment by aligoren** [comment] 2019-02-07 12:34
I think this isn't related to dev.to' RSS sources.

You can check by page source

![image](https://user-images.githubusercontent.com/4205423/52411723-c9a28d80-2aed-11e9-9108-b6831f631b7e.png)

**Comment by aspittel** [comment] 2019-02-07 19:08
Thanks for reporting this @IvanDelsinne!

**Comment by aligoren** [comment] 2019-02-07 19:22
@aspittel This shouldn't be labeled as a bug.

With [this](http://www.feedbucket.com/?src=https%3A%2F%2Fdev.to%2Ffeed) url you can check.

**Comment by maestromac** [comment] 2019-02-07 21:04
Thanks for pointing that out, @aligoren. 

@IvanDelsinne can you verify that this isn't a problem with Miniflux? I've tested it with feeder.co and I don't see any duplicates.

**Comment by IvanDelsinne** [comment] 2019-02-10 11:52
Few days passed, and I couldn't notice a duplicate again. I guess the dev.to polling failed once

**Comment by Zhao-Andy** [comment] 2019-02-15 18:11
Hey @IvanDelsinne, we're going to close this since it sounds like it's not reproducible. Feel free to open it again if it reappears.

**Closed by Zhao-Andy** 2019-02-15 18:11 UTC
Labels: bug
