### ISSUE TITLE
responsive issues in comment preview on mobile.

### ISSUE THREAD

**Issue by itsjzt** [thepracticaldev/dev.to#3264] opened 2019-06-22 11:15 UTC
**Describe the bug**

If you preview your comment which has image the image overflows.

**To Reproduce**

1. Open dev.to site in your phone
2. go to any post and add an image in comment.
3. click on preview.
4. the preview section will overflow according to the width of the image.

**Expected behavior**

Image shouldn't overflow

**Screenshots**

![Screenshot_20190622-164322_Firefox](https://user-images.githubusercontent.com/22629916/59963162-e6f55880-94de-11e9-8e4f-1cb7ce30a311.jpg)
![Screenshot_20190622-164313_Firefox](https://user-images.githubusercontent.com/22629916/59963166-ed83d000-94de-11e9-8d19-6e2c1660013a.jpg)

**Smartphone (please complete the following information):**

- Device: Samsung m30
- OS: Android 9
- Browser: Firefox
- Version: 67

**Additional context**

**Comment by maestromac** [comment] 2019-06-24 18:29
Thank you for the issue. This is duplicate of https://github.com/thepracticaldev/dev.to/issues/3085. Please continue the conversation there.

**Closed by maestromac** 2019-06-24 18:29 UTC
Labels: triage
