### ISSUE TITLE
Friend and _14_ others followed you

### ISSUE THREAD

**Issue by am-kantox** [thepracticaldev/dev.to#984] opened 2018-10-23 05:06 UTC
**‘Followed’ notification shows an incomplete amount of followers**
When 15+ people followed me in a row, without any intermediate action happened in between, the number sticks to 14.

**To Reproduce**

1. Make 1024 persons follow you in a row.
2. Click on 🔔 in the top right corner of the screen
3. See discouraging and frustrating “Friend and **14** others followed you”

**Expected behavior**
“We wait for your next sermon, your homily majesty” message or like

**Screenshots**
Trust me, it happens.

**How to fix**
In `app/views/notifications/_aggregated_follows.html.erb:39` there is the call to `<%= followers.size - 1 %>` which I was unable to realize where comes from. Basically, it should behave nearly the same as in reactions `app/models/reaction.rb:42`: `take(15)`.

I pretty fine understand the reasoning behind not returning the whole bunch of items, but the fix to return a real count will be very easy (it costs 1 additional `COUNT` query to the database.) Example as for the `Reaction` model:

```ruby
def self.for_display(user)
  includes(:reactable).
    where(reactable_type: "Article", user_id: user.id).
    where("created_at > ?", 5.days.ago).
    select("distinct on (reactable_id) *").
    take(15). # ⇐ HERE!
    tap do |records|
      count =
        if records.size < 15
          records.size
        else
          where(reactable_type: "Article", user_id: user.id).
          where("created_at > ?", 5.days.ago).
          count
        end
      records.extend(Module.new do
        def total_count_for_display
          count
        end
      end)
    end
end
```

Now the recordset returned has an additional method `total_count_for_display`, returning _the real count_.  In `erb` file the change would be straightforward:

```diff
- <%= followers.size - 1 %>
+ <%= followers.total_count_for_display - 1 %>
```

Note, that this fix has no impact for almost all cases when `records.size` is less than 15 it’s a NOOP.

**Comment by jessleenyc** [comment] 2018-10-23 16:34
Cool, this makes sense. Thanks for recommending a fix. @am-kantox would you want to submit a PR for this? Regardless, this is approved if anyone wants to grab it!

**Comment by am-kantox** [comment] 2018-10-24 03:38
Unfortunately, I don’t have an environment to test it since I am trying hard to quit ruby at all. Also, I am unsure where this `followers` variable comes from, I doubt `reactable_type: "Article"` is the right place, I have just posted the snippet as an example.

**Comment by juniordevlearning** [comment] 2018-11-02 12:51
i would like to test the code, is there a better idea then creating 16 github accounts and following myselfe on my local setup?

**Comment by am-kantox** [comment] 2018-11-02 13:12
@juniordevlearning I believe, in local you might simply produce 16 stubbed users and manually link them to be followers. Also, there should be an integration test checking that the page contains the text _“Donald Trump and 15 others”_.

**Comment by Zhao-Andy** [comment] 2018-11-02 13:46
@juniordevlearning our seed data will populate users for you, via `bin/rails db:seed`. If you've set up your environment based on our instructions though, you should have seed data created already. The command that did this in our setup guide was `bin/rails db:setup`.

Assuming you've set up your environment as per our guide and have all your [API keys needed for development](https://docs.dev.to/get-api-keys-dev-env), you'll have to do a few things to reproduce this:
1. Run your development server with `bin/rails server`
2. Clear any existing asynchronous jobs: `bin/rails job:clear`
3. Run the job worker: `bin/rails job:work`
4. Create an account via signing in on `localhost:3000` if you haven't already.
5. Run the console: `bin/rails console`
6. In console, have 16 users follow you:
```ruby
me = User.last
User.first(16).each { |user| user.follow(me) }
```
7. Wait a minute or two for the async jobs to complete
8. Visit `/notifications` and check out the follow notification.

From there you should be able to debug it.

**Comment by juniordevlearning** [comment] 2018-11-02 14:05
Hey, thx for both replys. I'll try it out and report back.

**Comment by juniordevlearning** [comment] 2018-11-02 14:33
I just tryed it, but i only have 10 users following me. Maybe there are only 11 users in db including my account? I also run the bin/rails db:seed task again. I am looking for the task now and see if i can change it so it creates 25 users.

**Comment by Zhao-Andy** [comment] 2018-11-02 14:36
Ah yeah, I forgot we recently changed it to 10 users. You can run this loop again:
https://github.com/thepracticaldev/dev.to/blob/master/db/seeds.rb#L24-L51

**Comment by juniordevlearning** [comment] 2018-11-05 09:10
Hey, yes i just changed the 10 to 25. But now i am stuck, i figured that the followers variable in the template is based on the @activities variable from the notifications_controller. The @activites variable gets a feed from StreamRails.
`   feed = StreamRails.feed_manager.get_notification_feed(@user.id)
    feed.get(limit: 45)["results"]`
But in the feed are only the last 15 users. So can we change the size of the feed? Or is it better to write a new method?

**Comment by am-kantox** [comment] 2018-11-05 09:36
> can we change the size of the feed?

No, it will drastically impact the performance. In the issue itself I described the way to go that should be easily adopted to this case. After the `feed` is there, you probably should check for an amount of items as shown in my snippet and if it is unclear whether there are more (>= 14 I’d guess) you should `extend` the respective part of that feed with the method returning the exact count.

**Comment by Zhao-Andy** [comment] 2018-11-05 18:56
@juniordevlearning we're actually going to rewrite our notification system, since we want to move off of using Stream (our current notification handler). If you're close to a PR though we're happy to merge it.

**Comment by juniordevlearning** [comment] 2018-11-06 10:05
No not really... I am not sure how to change the size of the feed from Stream.

**Comment by Zhao-Andy** [comment] 2018-11-28 16:57
This is fixed now!

**Closed by Zhao-Andy** 2018-11-28 16:57 UTC
Labels: approved
