### ISSUE TITLE
Possible Bug: Open content link on new tabs 

### ISSUE THREAD

**Issue by diarselimi** [thepracticaldev/dev.to#4921] opened 2019-11-25 13:02 UTC
**Describe the bug**
When I click on the links inside the content of any article then it redirects me to that link instead, I think it should open it in a new tab.

**To Reproduce**
Just click in any link inside any article.

**Expected behavior**
Should open the link in a new TAB.

**Screenshots**

**Desktop (please complete the following information):**

- OS: *
- Browser: *
- Version: *

**Comment by rhymes** [comment] 2019-11-25 13:33
Hi @diarselimi, thanks for your PR! It's not exactly a bug, it's more how browsers work ehhe.

I'm closing this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/1716

There has been an ongoing discussion about this feature, we'll probably end up implemeting that as a user setting...

**Closed by rhymes** 2019-11-25 13:33 UTC
Labels: triage
