### ISSUE TITLE
Ability to render article card on other sites.

### ISSUE THREAD

**Issue by BassemMohamed** [thepracticaldev/dev.to#3676] opened 2019-08-10 15:09 UTC
**Is your feature request related to a problem? Please describe.**

It would be really cool if I could link articles in another site (eg: personal website) by rendering the article card. ( Same way as rendering facebook's share button )

That is what I mean by article card: 
![Screen Shot 2019-08-05 at 10 06 40 AM](https://user-images.githubusercontent.com/17043634/62823469-5c9dac80-bb91-11e9-98b4-80b7bb6f910d.png)

**Describe the solution you'd like**
Maybe a Javascript that could be embedded on any site to enable rendering articles in this card format.

**Comment by jessleenyc** [comment] 2019-08-12 21:44
Hey @BassemMohamed, thanks for the request! I believe this is a duplicate of https://github.com/thepracticaldev/dev.to/issues/1445 so I'm going to close this issue in favor of the original.

**Closed by jessleenyc** 2019-08-12 21:44 UTC
Labels: triage
