### ISSUE TITLE
Make PWA icon android adaptive.

### ISSUE THREAD

**Issue by TheMisir** [thepracticaldev/dev.to#4111] opened 2019-09-25 22:04 UTC
Here's more about that: https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/

**Comment by maestromac** [comment] 2019-09-26 21:03
I believe this was already resolved with https://github.com/thepracticaldev/dev.to/pull/3875. Does the icon look unmasked on your end @TheMisir ?

**Comment by TheMisir** [comment] 2019-09-27 08:49
![](https://i.imgur.com/oqrY4f9_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

@maestromac

**Comment by Glennmen** [comment] 2019-09-27 08:56
Could this be because icon size 192x192 doesn't have the `purpose` tag?
https://github.com/thepracticaldev/dev.to/blob/aa9f03740e341f39cb9619ea7ad48890bbad5d2f/app/assets/javascripts/manifest.json.erb#L10-L14

**Comment by Amorpheuz** [comment] 2019-09-27 16:13
Yup, `purpose` tag is required to define how the image should be used. Adding the `maskable` purpose should allow it to scale; though will have to check if the word `DEV` correctly fits into the appropriate dimensions as indicated [here](https://www.w3.org/TR/appmanifest/#icon-masks).

Can read https://www.w3.org/TR/appmanifest/#icon-masks and https://www.w3.org/TR/appmanifest/#icons-member for more info. Btw it also appears like that on my screen too; thought was intended.

**Comment by Link2Twenty** [comment] 2019-09-30 15:52
192 is size used by most phones too. @Glennmen I think that change should sort it.

**Comment by Glennmen** [comment] 2019-09-30 18:21
I will try to make a PR for it tomorrow 😉

**Closed** 2019-10-08 15:31 UTC
Labels: help wanted
