### ISSUE TITLE
No reply button for deep 2 replies

### ISSUE THREAD

**Issue by Defman21** [thepracticaldev/dev.to#174] opened 2018-03-06 21:38 UTC
# _BUG_
### Current Behavior
No Reply button for deep 2 replies (it's there for deep 1, deep 3, etc.)

### Expected Behavior
The button should be there.

### Additional Info (steps to replicate, device/browser, helpful links)

Firefox 60.

I see this issue there: https://dev.to/ben/which-mainstream-programming-language-has-the-ugliest-syntax--31l/comments

### Screenshots

![image](https://user-images.githubusercontent.com/7100645/37059934-d1889bfa-219f-11e8-8737-225520f80491.png)

![image](https://user-images.githubusercontent.com/7100645/37059901-b6e75ae8-219f-11e8-8bf8-1eec93bd0d9a.png)

**Comment by Zhao-Andy** [comment] 2018-03-06 21:41
Thanks for the heads up. A short term solution is clicking the chevron and going to the permalink view of the comment.

**Comment by jessleenyc** [comment] 2018-10-04 19:11
Hey @Defman21, removing the reply button is actually intentional here. @benhalpern can jump in with some thoughts if you have any questions. Closing for now.

**Closed by jessleenyc** 2018-10-04 19:11 UTC
Labels: bug

**Comment by Defman21** [comment] 2018-10-05 06:28
I do. For what reasons? That looks like an UX bug to me.

**Comment by jwedel** [comment] 2019-01-14 07:33
@jessleenyc @benhalpern Yep, I was just about to create a bug for that. If it's not a bug, it's at least a UX issue.

Consider the [following thread](https://dev.to/stealthmusic/enterprise-software-development-383o):
![image](https://user-images.githubusercontent.com/4849728/51100511-bb0ad400-17d6-11e9-8343-6631f81df063.png)

I want to add a second reply to "Sandor Dargo". The only reply button however is for "AsParallel". But I don't want to reply this account.

It is very unclear why I can't (or shouldn't be able to) do that.

**Comment by Defman21** [comment] 2019-02-13 06:19
@benhalpern @jessleenyc you didn't answer me. What's the reason for not having a reply button in this case?

**Comment by Defman21** [comment] 2019-02-13 06:26
Oh I understand now. 2 deep replies starts a thread and it looks like you can't go further. So the Reply button actually replies to the thread and not to the comment which contains the button.
