### ISSUE TITLE
[Feature request] Customize RSS feed based on tag

### ISSUE THREAD

**Issue by IvanDelsinne** [thepracticaldev/dev.to#201] opened 2018-04-20 16:41 UTC
### Request or User Story

I'm using a RSS feed reader to gather all my news sources and feeds, and I'd really like a way to subscribe to my dev.to feed somehow, or a customized feed based on tags.

### Definition of Done

When we have an available RSS feed

**Comment by Zhao-Andy** [comment] 2018-04-24 16:38
Hey Ivan, thanks for the feedback. We have an RSS feed of the homepage, but it's not really customizable yet: https://dev.to/feed

We're going to backlog this for now. :)

**Comment by c33s** [comment] 2018-08-22 13:25
@jessleenyc #201 is duplicate of #201? ;)

**Comment by jessleenyc** [comment] 2018-08-22 14:00
haha oops! it's a duplicate of https://github.com/thepracticaldev/dev.to/issues/156!!!!

**Comment by c33s** [comment] 2018-08-22 14:09
hmm, is it really a duplicate? #156 is only a subset of #201. 

- subscribe tags 
- subscribe my/someones posts
- subscribe my/someones feed

**Comment by timnolte** [comment] 2018-08-22 23:46
Following this.

**Comment by shanalikhan** [comment] 2018-09-05 20:00
I agree with @turquoise-turtle , i also use Feedly and really want my customized feed there. When even i open Feedly i got many posts from dev.to.

**Comment by maestromac** [comment] 2018-12-04 23:18
not stale

**Comment by maestromac** [comment] 2019-02-27 16:20
I'm updating this issue with an more appropriate title.

**Comment by wesdelp** [comment] 2019-03-11 17:44
I would like this feature as well and would be willing to give it a shot if it is approved for contributions!

**Comment by maestromac** [comment] 2019-03-19 17:24
Feel free to give it a try @wesdelp !

**Comment by wesdelp** [comment] 2019-05-01 18:33
@IvanDelsinne @maestromac first pass here https://github.com/thepracticaldev/dev.to/pull/2634. I kept it simple with just the ability to filter a feed by a specified tag. Multiple tags could be accomplished for now by just subscribing to multiple feeds 👌

**Closed** 2019-05-03 15:35 UTC
Labels: feature request
