### ISSUE TITLE
Preview mode of basic markdown editor has white code blocks in dark mode

### ISSUE THREAD

**Issue by emgoto** [thepracticaldev/dev.to#8268] opened 2020-06-04 12:31 UTC
**Describe the bug**

When using the basic markdown editor (it looks super nice by the way!) in dark mode, the code blocks are not dark mode as you would expect.

**To Reproduce**

* Be using a dark theme ("night theme")
* Edit a post thats in my dashboard via my RSS feed
* See new basic markdown editor
* Scroll to a code block
* See the whiteness and be blinded

Side note, the sidebar also tells me that I can change to using the rich + markdown editor instead in the settings, but if I go to my settings, that option is already selected. I'm not sure if this is a side effect of having created the post via RSS, and it doesnt allow me to use the rich option?

**Expected behavior**

The preview mode should show the code blocks in dark mode (like they show up in the final post once it's published).

**Screenshots**

<img width="1050" alt="Screen Shot 2020-06-04 at 10 25 56 pm" src="https://user-images.githubusercontent.com/33337378/83756569-93a9f500-a6b2-11ea-956d-e3bfd90ace31.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Firefox
- Version:

**Comment by rhymes** [comment] 2020-06-04 12:45
Hi @emgoto, thanks for the report! I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/8206

Feel free to add a comment there as it's always helpful :)

**Comment by rhymes** [comment] 2020-06-04 12:46
> Side note, the sidebar also tells me that I can change to using the rich + markdown editor instead in the settings, but if I go to my settings, that option is already selected. I'm not sure if this is a side effect of having created the post via RSS, and it doesnt allow me to use the rich option?

This is because an article is tied to the version it was created with. We should probably clarify that in the side bar

**Closed by rhymes** 2020-06-04 12:45 UTC
Labels: triage
