### ISSUE TITLE
Ability to view all articles active user has 'hearted'

### ISSUE THREAD

**Issue by Nikla436** [thepracticaldev/dev.to#5580] opened 2020-01-19 04:08 UTC
**Is your feature request related to a problem? Please describe.**
No, not related to a bug.

**Describe the solution you'd like**
I often will 'heart' things I enjoyed and may want to look back on later, and would like a way to view all things I've reacted to. (hearted, unicorn, etc).

Often I'll remove things from my reading list when finished, but would like a way to get back to what I've enjoyed before.

Ex: Reddit will allow you to view your history, upvotes, downvotes, etc. That would be nice here as well.

**Comment by rhymes** [comment] 2020-01-19 11:52
Thanks @Nikla436 for taking the time to open this. 

I'm going to close it as a duplicate of this https://github.com/thepracticaldev/dev.to/issues/1806 - it'd be awesome if you'd add the description you added here there as well.

**Closed by rhymes** 2020-01-19 11:52 UTC
Labels: triage
