### ISSUE TITLE
"About DEV Listings" Button Color - Pink Theme

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#3667] opened 2019-08-09 15:58 UTC
**Describe the bug**
It's very hard to see the button on pink mode. 

**To Reproduce**
Visit any listings link: try this example - https://dev.to/listings/collabs/contributors-wanted-sample-programs-in-every-language-281c

**Expected behavior**

Add a color to the button to make it read easier, account for all themes.
Theming docs: https://docs.dev.to/design/theming/

**Screenshots**

![](https://cl.ly/e8a0b9068193/download/Image%202019-08-09%20at%2011.53.52%20AM.png)

**Comment by erdahuja** [comment] 2019-08-09 16:46
The button background colour if set to match theme, looks great and consistent.
![image](https://user-images.githubusercontent.com/15168716/62794997-3e816f00-baf3-11e9-8014-77219ee362ab.png)

**Comment by jessleenyc** [comment] 2019-08-09 17:55
@erdahuja are you saying that you can't reproduce the bug?

**Comment by erdahuja** [comment] 2019-08-10 03:38
@jessleenyc It is reproducible, I changed the background-color of button to see how it should be fixed. Turns out theme color if matched with bg-color of button. It fixes it.

**Comment by jessleenyc** [comment] 2019-08-12 18:49
Got it, yeah! That makes sense. Do you want to submit a PR?

**Comment by erdahuja** [comment] 2019-08-13 12:40
@jessleenyc Sure. Can you help me with a good starting point in this project? It's my first PR here.

**Comment by Glennmen** [comment] 2019-08-13 12:45
@erdahuja The HTML can be found here:
https://github.com/thepracticaldev/dev.to/blob/e9db50b7c9e98b0b77d83e3285e22e0389663e7f/app/javascript/listings/listings.jsx#L440-L445

And the CSS in question here:
https://github.com/thepracticaldev/dev.to/blob/e9db50b7c9e98b0b77d83e3285e22e0389663e7f/app/assets/stylesheets/classified_listings.scss#L531-L552

**Comment by allmanaj** [comment] 2019-10-01 18:12
I'll work on this one! 😁

**Comment by Aswathprabhu** [comment] 2019-10-02 06:13
@jessleenyc I've fixed this issue and raised my [PR(4190)](https://github.com/thepracticaldev/dev.to/pull/4190)

**Comment by rhymes** [comment] 2019-10-02 08:44
@allmanaj it looks like @Aswathprabhu sent a PR about this, I'm sorry.

There are a few other issues related to https://github.com/thepracticaldev/dev.to/labels/area%3A%20themes if you want to try to tackle any

**Closed** 2019-10-02 18:15 UTC
Labels: area: themes, good first issue, hacktoberfest, help wanted, type: bug
