### ISSUE TITLE
API auth error with NodeJS

### ISSUE THREAD

**Issue by miku86** [thepracticaldev/dev.to#4457] opened 2019-10-16 08:11 UTC
Hey guys,

don't know if this is some sort of bug.
I searched for other API issues and saw,
that other people are actually using the API,
so I think the problem is on my side.

I created a small Node app to fetch my posts via the API.

```js
const fetch = require('node-fetch');
require('dotenv').config();

const API_URL = "https://dev.to/api";
const PATH_ALL_ARTICLES = "/articles/me/all";
const AUTH_QUERY = `api_key=${process.env.API_TOKEN}`;
const URL_ALL_ARTICLES = `${API_URL}${PATH_ALL_ARTICLES}?${AUTH_QUERY}`;

const getAllArticles = async (url) => {
  try {
    const response = await fetch(url);
    console.log(response);
  } catch (err) {
    console.log(err);
  }
}

getAllArticles(URL_ALL_ARTICLES);
```

If I run it with Node, I get `{"error":"unauthorized","status":401}`.
The URL is correct, I can open it and see the correct results in the browser like expected.

I had a look at the actual requests in Firefox & Chromium and found out, that I have to have a cookie named "_PracticalDeveloper_session" to get the data.
If I delete the cookie, I get `{"error":"unauthorized","status":401}` when going to the URL that worked before.

**Expected behavior**

Sending a request with my API token in Node results in getting articles back instead of an auth error.

**What I tried to solve the problem**
- Changed the fetch library to axios: same auth error
- Tried Postman with the same  URL: same auth error
- Built a JS script (including credentials) in a HTML file: same auth error
- Created a new token: same auth error

**Desktop (please complete the following information):**

- OS: 5.3.6-arch1-1-ARCH
- Node: v12.12.0
- node-fetch: 2.6.0
- axios: 0.19.0

Thank you :)
Michael

**Comment by rhymes** [comment] 2019-10-16 08:37
Hi @miku86, at a first glance of the code, the issue is that the API key should be in a header, not in the request URL. You can check more info about how to authenticate in the docs: https://docs.dev.to/api/#section/Authentication/api_key 

I've noticed there's a documentation error in the API docs example in the `me` section. I'll update them promptly.

Let me know if it works

**Comment by miku86** [comment] 2019-10-16 09:10
@rhymes 

that was an easy one :1st_place_medal: 
Thank you!

Moved the token into the header and its's working.

```js
await fetch(url, { 
  headers: { 
    "api-key": process.env.API_TOKEN
  }
});
```

When I search for `header` in the docs, I only get one result,
therefore I think it would be useful for other people, 
if this fact would be highlighted.

Thank you,
Michael

**Comment by rhymes** [comment] 2019-10-16 09:33
Glad it worked, thank you for raising the issue! I'm going to close this :)

**Closed by rhymes** 2019-10-16 09:33 UTC
Labels: triage
