### ISSUE TITLE
Can't escape triple backtick inside markdown code block

### ISSUE THREAD

**Issue by raddevon** [thepracticaldev/dev.to#4400] opened 2019-10-13 23:45 UTC
**Can't escape triple backtick inside markdown code block**

I'd like to have a fenced markdown code block which itself includes an escaped fence like this:

~~~markdown
# Some content

```
alert('fenced code');
```
~~~

To achieve the above example, I've used `~~~` to fence the block which allows me to use `` ``` `` unescaped inside the block. When I try this in the Dev.to editor, the initial fence opens the code block as expected, but the first backtick fence closes the codeblock. For example, this code:
````
~~~
test
```
test
```
test
~~~
````

produces this:
![Escaped code fence result on dev.to](https://user-images.githubusercontent.com/2027711/66723744-97120880-edd1-11e9-88ac-3d2fe11d2965.png)

I've tried other approaches to escaping the backtick codefence as well. Surrounding each triple with a double backtick avoids ending the code block, but all the backticks are reproduced on the page like this:
![Attempt at escaping triple backticks with double backticks](https://user-images.githubusercontent.com/2027711/66723787-261f2080-edd2-11e9-91ee-9cb2ebac8517.png)

I've also tried indenting the block instead of fencing it. This gets me closest to the desired result — it allows me to include the backticks — but it still breaks the code block:
![Backticks inside indented markdown code block](https://user-images.githubusercontent.com/2027711/66723813-6b435280-edd2-11e9-9e86-5d8178494430.png)

**To Reproduce**

1. Create or edit a post
1. Create a code block fenced by `~~~`
1. Attempt to include `` ``` `` inside the code block using one of the methods described above
1. Click "Preview" to observe the result

**Expected behavior**

`` ``` `` would appear inside the fenced code block.

**Screenshots**

_(See above)_

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.5 (18F203
- Browser: Chrome
- Version: 77.0.3865.120

**Comment by rhymes** [comment] 2019-10-14 13:28
Hi @raddevon, thanks for the reporting! is this a duplicate of https://github.com/thepracticaldev/dev.to/issues/4400 ? Let me know if there's anything different going on

**Comment by raddevon** [comment] 2019-10-15 01:01
@rhymes This is similar to #3648 although it doesn't seem that user attempted to fence with `~~~` to be able to get triple backticks without escaping. That might be a separate issue? Not sure.

**Closed** 2019-11-05 19:15 UTC
Labels: type: bug
