### ISSUE TITLE
Show random posts

### ISSUE THREAD

**Issue by mzaini30** [thepracticaldev/dev.to#6091] opened 2020-02-16 10:56 UTC
![Alt Text](https://dev-to-uploads.s3.amazonaws.com/i/62l5xjh6h2ky8pfnlqsf.jpg)

**Comment by rhymes** [comment] 2020-02-16 19:33
Hi @mzaini30, thanks for requesting this feature. As I believe it's a duplicate of https://github.com/thepracticaldev/dev.to/issues/5435 I'm going to close this.

Let me know if it's not the case.

**Closed by rhymes** 2020-02-16 19:33 UTC
Labels: triage
