### ISSUE TITLE
Improving Quality Post on Tags

### ISSUE THREAD

**Issue by shanalikhan** [thepracticaldev/dev.to#606] opened 2018-09-05 15:06 UTC
There are many articles which I think doesn't fit into tags the owner has set in order to get views etc.
It would be great if the platform provides some limitations to let article owner define tag more precisely. They can be multiple ways.

Limit the tags to 2 tags per article so article owner thinks the topics more precisely before publishing.
In this way, the user will get more accurate articles for the topic he has subscribed. It might decrease the tag quantity but it will definitely improve the quality of articles on which user has subscribed.

**Comment by AntonyGarand** [comment] 2018-09-05 18:39
I disagree about limiting the tags to 2, it is easy to justify having few more, such as javascript, react, showdev, opensource

There could be a "Suggest removing X tag" button though, where after few reports the tag is removed or flagged for moderation!

**Comment by benhalpern** [comment] 2018-09-05 18:45
Yeah I think @AntonyGarand is thinking about this the right way.

Agree with the general problem statement. We've been low-key moderating this since day one but it's not really keeping up with scale. We will need to add some functionality to keep this working well.

**Comment by shanalikhan** [comment] 2018-09-05 19:58
@AntonyGarand 
> javascript, react, showdev, opensource

Why not limit it to **react, opensource** - The react, javascript might be the same. But making a tag with react instead of javascript makes it more accurate according to content.

"Suggest removing X tag" can be one option. 


> We will need to add some functionality to keep this working well.

Yes, I recently joined this community and found these things, it's better to control or manage them unlike medium or any other platform.

**Comment by jonathan-irvin** [comment] 2018-09-06 20:49
React = Javascript
JavaScript != React

I look at javascript as a broad tag and React as a more focused tag.

**Comment by misterhtmlcss** [comment] 2018-09-10 22:53
@shanalikhan I can't disagree with you more and I totally agree with @benhalpern @jonathan-irvin. Heres why.
1. Many things can be compiled into a language such as React, such as TypeScript.
2. If something is opensource it's potentially an invitation to action such that @jonathan-irvin would likely even be able to valid that point of view, then you have intent in the tag, such as 'healthydebate' which I personally love. So you have two tags for intention and you have maybe two more for topic relation ex. HTML, CSS, but what if the CSS is SASS? What if you are compiling the CSS into JS? What if it's Webpack, but it's not Webpack on Create React App... I could go on and on, but I think I have made my second point.

3. The issue isn't NUMBER of tags, it's the QUALITY of the tagging. This absolutely is always a problem on any platform where user interests can diverge from platform/community interests ex. fakenews anyone? 

My vote: I am very supportive of two approaches: 
1. We do like stackexchange and we have similar manpower driven methodology OR
2. We add an edit button that allows the user to remove the tag and we should just have a basic algo that says if x % of users 'vote' by clicking to remove then it get's removed automatically. 

Thoughts?

**Comment by jessleenyc** [comment] 2018-09-11 14:57
@shanalikhan we have a concept of tag aliases and i just added ml as an alias for machinelearning. This _should_ make it appear now.

**Comment by shanalikhan** [comment] 2018-09-11 15:01
Yes it works, Thanks

@jessleenyc

**Comment by jessleenyc** [comment] 2018-12-11 15:22
Hey @shanalikhan, we're closing this issue because we now have tag moderators that have the ability to remove tags from posts if they are not tagged appropriately. This should result in better tags on posts across the board which seems to be the main concern here.

**Closed by jessleenyc** 2018-12-11 15:22 UTC
Labels: community discussion
