### ISSUE TITLE
Non-centered footer in Articles Dashboard

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#3112] opened 2019-06-10 20:56 UTC
**Describe the bug**
In `dev.to/dashboard`, the footer is aligned more to the right compared to the center column of articles. This happens between the widths of `950` and `1119` and it seems fine for anything wider or narrower.

**To Reproduce**

1. Go to 'dev.to/dashboard'
2. Adjust your width to between 950 and 1119
3. Scroll down to the bottom
4. See footer

**Expected behavior**
The footer should be centered in pages like `/dashboard` where there are no cards to the right or left of the center column.

**Screenshots**
![Screen Shot 2019-06-10 at 16 58 08](https://user-images.githubusercontent.com/13403332/59226431-fbf9ef80-8ba0-11e9-9251-279507f8bc81.png)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 75

**Additional context**
 Note that the footer is used all throughout DEV and is not always center aligned depending on what page you're on.

**Comment by arku** [comment] 2019-06-11 01:50
Interesting. This is how it looks to me on Firefox (I am on a Mac).

![image](https://user-images.githubusercontent.com/7039523/59237858-5c992480-8bc1-11e9-8cd3-13590b9cd2c1.png)

**Comment by mariocsee** [comment] 2019-06-11 13:44
@arku Just to check, did you get to adjust your width to between 950 and 1119?

**Comment by NedyUdombat** [comment] 2019-06-13 22:41
Hi, I would like to work on this. But I am having troubles setting up the ruby application on my local machine, any form of assistance will he highly appreciated

**Comment by arku** [comment] 2019-06-13 23:25
> Just to check, did you get to adjust your width to between 950 and 1119?

Ah, no I didn't. Thanks for adding the resizing step to the Reproduction steps.

I am able to reproduce the issue.

![image](https://user-images.githubusercontent.com/7039523/59473497-47620700-8e08-11e9-9ca7-9a8a33432d3c.png)

**Comment by arku** [comment] 2019-06-13 23:26
@NedyUdombat Thanks for offering to help! It would be helpful if you could let us know what issue you're running into.

**Comment by NedyUdombat** [comment] 2019-06-13 23:55
@arku I am trying to setup the database and it is showing me this. If you can help I would appreciate
![Screenshot 2019-06-14 at 12 53 58 AM](https://user-images.githubusercontent.com/31692932/59474501-01746580-8e3f-11e9-8353-432c12a94295.png)

**Comment by rhymes** [comment] 2019-06-14 08:48
@NedyUdombat what happens if you issue `createdb TestABC` from the command line? I think it's telling you there's a password required for your installation of PostgreSQL. 

You can check the DEV installation docs to see how to provide the password to the Rails application https://docs.dev.to/installation/postgresql/#configuration

**Comment by reesecode** [comment] 2019-09-30 17:39
Ah yep, just replicated it. Looks like @media tags fighting. There's a very unneeded `margin-left: 310px;` in there for the @media tag for `@media screen and (max-width: 1119px) and (min-width: 950px)
footer .container.centered-footer {` I'll try to give my shot at tackling it in a bit.

**Comment by jacobherrington** [comment] 2019-10-02 18:55
I believe #3965 resolved this -- is anyone still able to replicate this issue in production or with the current master branch?

**Comment by akshayymahajan** [comment] 2019-10-04 03:21
Still able to replicate the issue. Would like to work on this..

![image](https://user-images.githubusercontent.com/8535863/66178766-12621480-e684-11e9-8471-2dcfbb2c330e.png)

**Comment by akshayymahajan** [comment] 2019-10-07 03:45
Is anyone still working on this? If not, I would like to tackle this..

**Comment by akshayymahajan** [comment] 2019-10-07 09:29
@rhymes Yes. My bad, I thought #4153 was merged. It should fix the issue..

**Comment by maestromac** [comment] 2019-10-07 13:50
Resolved with https://github.com/thepracticaldev/dev.to/pull/4153

**Closed by maestromac** 2019-10-07 13:50 UTC
Labels: good first issue, hacktoberfest, help wanted, tech: html/css, type: bug
