### ISSUE TITLE
Add the posibility to edit in preview mode an article

### ISSUE THREAD

**Issue by wolfiton** [thepracticaldev/dev.to#6254] opened 2020-02-23 17:30 UTC
**Is your feature request related to a problem? Please describe.**

It would be great to be able to edit the article and have the preview on as well.

**Describe the solution you'd like**

So basically what I am saying is to be able to edit in preview mode(markdown preview) an article.

**Describe alternatives you've considered**

To integrate preview mode into the edit mode by default so that when you edit you already know how your article will look like.

**Additional context**

Current edit method
![current_edit_method](https://user-images.githubusercontent.com/5812565/75116600-c9325180-5672-11ea-8c0c-0de7d60e424b.png)

My new proposition for this method

![my_feature_proposition](https://user-images.githubusercontent.com/5812565/75116611-e49d5c80-5672-11ea-8102-88a908957347.png)

**Comment by rhymes** [comment] 2020-02-23 21:43
Hi @wolfiton, thanks for opening this feature request. It seems that from time to time this idea pops up as it's understandably interesting for writers. As I believe this is a duplicate of https://github.com/thepracticaldev/dev.to/issues/3049 I'm going to close it and ask you if you can add your proposal to #3049 as a comment. 

Thanks a lot!

**Closed by rhymes** 2020-02-23 21:43 UTC
Labels: triage

**Comment by wolfiton** [comment] 2020-02-24 14:56
Thanks, @rhymes, 
For the quick response, I will folow your suggestion and add my comment to the old issue.
