### ISSUE TITLE
Saving articles as lists

### ISSUE THREAD

**Issue by kodaman2** [thepracticaldev/dev.to#3231] opened 2019-06-19 09:15 UTC
I searched on current feature requests and didn't find anything like it, or if this is already possible on the site as it is. I apologize in advance. : ) I realize this might create a layer of complexity, and I really do love the simplicity of dev.to but having those articles saved for later might be really useful for me.

**Is your feature request related to a problem? Please describe.**
 
I don't know how much of a problem this is for others, but when I find a useful article I save it to read it later, and most often than not those articles can be itemized like if is python I'd like to have my saved articles by topic/folder rather than tags. Once I archive the article is gone, and the only way to find it again is to search for it or search on tags and if I get lucky and I remember enough about the title I might find it again.

**Describe the solution you'd like**

Saving to a list sort of like the reading list, but with an editable topic name, for example "Useful beginner articles", I can save articles that I think would be useful for beginners even when tags do not match beginner or python.

**Describe alternatives you've considered**

Only way I can think of at the moment would be to manually copy links somewhere else like google keep or evernote.

**Additional context**

Similar to folders on imgur, or lists on twitter.

**Comment by maestromac** [comment] 2019-06-25 14:10
Thank you for this issue @kodaman2 . A similar issue was already created. You are welcomed and encouraged to continue the conversation there :)

Duplicate of https://github.com/thepracticaldev/dev.to/issues/710

**Closed by maestromac** 2019-06-25 14:10 UTC
Labels: triage
