### ISSUE TITLE
Support <details>/<summary> tags in markdown

### ISSUE THREAD

**Issue by jessleenyc** [thepracticaldev/dev.to#2045] opened 2019-03-12 19:21 UTC
**Is your feature request related to a problem? Please describe.**
<details>/<summary> tags are support in github markdown and I'd like to use them on DEV as well.

**Comment by mariocsee** [comment] 2019-03-12 20:33
should these tags be supported in all or certain parts of the site that support markdown? (i.e articles, comments, chat messages)

**Comment by Link2Twenty** [comment] 2019-03-12 20:35
Will a polyfill be used for IE11 and Edge?

**Comment by maestromac** [comment] 2019-03-22 18:31
[Seems necessary](https://caniuse.com/#feat=details) to use polyfill

**Comment by rhymes** [comment] 2019-03-22 18:40
Threaded comments were implemented with details/summary and IIRC Ben didn't use polyfills because they just look expanded in IE11. On this note, can't we just leave it as it is and people with IE11/Edge will get the spoilers 😅 ?

**Comment by Link2Twenty** [comment] 2019-03-22 18:52
Slightly different I think, that being said we don't support IE and edge is moving to blink soon so will then support everything 😁

**Comment by sw-yx** [comment] 2019-03-22 23:44
yea hello i was the original suggester of this issue, and i only really care about this in posts. i do pretty longform posts :)

**Comment by aspittel** [comment] 2019-03-22 23:46
This is super helpful for having course and workshop material -- I use these all the time on GitHub in lesson plans! +1 for this feature!

**Comment by AlbertoPdRF** [comment] 2020-06-26 00:28
I think this issue is a duplicate of #947.

**Comment by rhymes** [comment] 2020-06-26 09:45
Good call @AlbertoPdRF, going to close it as such!

**Closed by rhymes** 2020-06-26 09:45 UTC
Labels: area: publishing experience, future, ready for dev, tech: ruby, type: feature request
