### ISSUE TITLE
Privacy Badger considers dev.to a tracker

### ISSUE THREAD

**Issue by sztomi** [thepracticaldev/dev.to#1796] opened 2019-02-13 15:18 UTC
> Before creating a bug report, try disabling browser extensions to see if the bug is still present.

^ This report is specifically about compatibility with a popular privacy extension, so I'm skipping this step.

**Describe the bug**

[Privacy Badger](https://www.eff.org/privacybadger) is a popular set-and-forget privacy extension for Google Chrome and Firefox. It differs from other blockers in that there is no fixed blacklisting of trackers. The extension monitors websites for tracking behavior and blocks them based on what it observed. 

*dev.to happens to be detected as a tracker by Privacy Badger*.

Usually the site works normally despite the blocking, but there is some broken behavior, too (see below).

**To Reproduce**

1. Install Privacy Badger
2. Browse dev.to for a while, until the extension changes the state for dev.to

To trigger the broken behavior when the blocking is active:

1. Visit an article while the blocking is active, e.g. https://dev.to/uf4no/my-kubuntu-osx-look-alike-desktop-setup-219g (I just verified the bahavior with this one, but probably any will work)
1. Click on the first image
1. Click on the back button
1. The "You are not connected to the Internet" page will be triggered
1. Refreshing the page keeps the not connected state
1. The only way to escape that is to copy the address and navigate to it in a new tab.

**Expected behavior**

I'm guessing this is a false positive by Privacy Badger (although I'm not familiar with the business model of the site, but from what I've seen it's not based on tracking the users). The solution is either to figure out what causes this detection and either or remove that behaviour, or work with Privacy Badger devs to fix it on their side. 

If it's *not* a false positive, then dev.to either:

  * should consider not tracking its users
  * should work properly with trackers blocked

**Screenshots**

![image](https://user-images.githubusercontent.com/240594/52720672-56df5980-2fa8-11e9-9ef5-15b5e8694c9b.png)

**Desktop (please complete the following information):**

- OS: Linux (but observed on other platforms)
- Browser: Firefox
- Version: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

**Additional context**

https://www.eff.org/privacybadger/faq#I-found-a-bug!-What-do-I-do-now
https://github.com/EFForg/privacybadger

**Comment by abraham** [comment] 2019-02-13 16:17
I couldn't reproduce this in Chrome.

**Comment by sztomi** [comment] 2019-02-13 17:45
You can emulate the behavior if you set dev.to to manual blocking (it does take some time for PB to kick its autodetection).

**Comment by Link2Twenty** [comment] 2019-02-14 14:15
Is it the default no connection page or the dev.to one?

**Comment by Zhao-Andy** [comment] 2019-02-14 17:10
FWIW I couldn't reproduce this on Chrome and Firefox Developer Edition. 

As @Link2Twenty mentioned, it might be related to service workers. We had a previous issue (https://github.com/thepracticaldev/dev.to/issues/128) before where Privacy Badger had issues with service workers in general. I think they may have patched it, but it's been a while so I'm not sure.

**Comment by sztomi** [comment] 2019-02-14 17:44
Happy to provide more info or a screenrecording if you have issues with reproducing.

**Comment by ghostwords** [comment] 2019-02-15 21:31
Yep, this is a Firefox-specific Service Workers bug: https://github.com/EFForg/privacybadger/issues/1144#issuecomment-436444285. Reproducing it is a bit tricky as it requires you to "warm up" the worker. You can see https://bugzilla.mozilla.org/show_bug.cgi?id=1499523 for more information.

We haven't patched it yet in Privacy Badger but hope to soon as it affects all sites that use Service Workers.

**Comment by jessleenyc** [comment] 2019-02-19 15:27
Thanks everyone. Looks like this is out of our hands so I'm going to close this issue.

**Closed by jessleenyc** 2019-02-19 15:27 UTC
Labels: bug
