### ISSUE TITLE
Automatically Remove Reading List items if post no longer exists

### ISSUE THREAD

**Issue by 12vanblart** [thepracticaldev/dev.to#5998] opened 2020-02-10 14:13 UTC
**Is your feature request related to a problem? Please describe.**

I was scrolling through my Reading list and there were a handful of older posts that I would click on and be taken to the 404 page. Going "back" to the reading list would lose my scroll placement and require a refresh to remove other articles that I had archived until I refreshed the page. 

**Describe the solution you'd like**

It'd be nice if dead links would be automatically removed/archived from my Reading list. (At least if the post was removed; Maybe not if it was simple set to unpublished? - not exactly sure how that interaction would work)

**Describe alternatives you've considered**

An alternative would be somehow maintaining scroll position when going back to the Reading list - this would at least make it easier to pick up where I left off.

**Comment by rhymes** [comment] 2020-02-10 15:18
Hi @12vanblart, I definitely have some of those entries, unfortunately it's a known issue: https://github.com/thepracticaldev/dev.to/issues/1641

I'm going to close this as a duplicate of the earlier issues, which also contains a conversation on what's going on. Let me know if it's not the case

**Closed by rhymes** 2020-02-10 15:18 UTC
Labels: triage
