### ISSUE TITLE
Cover image missing when you share a post to Pinterest

### ISSUE THREAD

**Issue by audreyr** [thepracticaldev/dev.to#7314] opened 2020-04-15 23:28 UTC
**Describe the bug**

When you try to pin a Dev.to post to Pinterest, if the only image is the cover image, the cover image doesn't show up in the "Choose a Pin to save" menu of the Pinterest Chrome extension. This makes it hard to use Pinterest to share my blog posts with my followers there.

I'm hoping to share some of the crafty/artsy things I'm making during #100DaysOfCode on Pinterest, and having to come up with both a cover image and an in-post image is my workaround for now. But it would be really nice if the cover image were pinnable.

**To Reproduce**

1. Install the [official Pinterest Chrome extension](https://chrome.google.com/webstore/detail/pinterest-save-button/gpdjojdkbbmdfjfahjcgigfpmkopogic?hl=en)
2. Click the "P" button from the extension to pin https://dev.to/feldroy/100daysofcode-for-the-experienced-developer-22cm
3. Notice how the cover image doesn't show up in "Choose a Pin to save".

<img width="1623" alt="Screen Shot 2020-04-15 at 16 17 26" src="https://user-images.githubusercontent.com/74739/79398348-59836900-7f35-11ea-9831-5e5624ff150f.png">

**Expected behavior**

I expected the cover image to show up as the image for the Pin.

**Desktop (please complete the following information):**

- OS: macOS Mojave 10.14.6
- Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Additional context**

More info on how Pinterest fits into my #100DaysOfCode Dev.to blogging workflow: https://gist.github.com/audreyr/fc58e8bf892cddd6e84c970b0432d834

**Comment by citizen428** [comment] 2020-04-16 04:12
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by benhalpern** [comment] 2020-04-18 17:23
Hmmmmm I think that is because the cover image is currently included as a _background image_. We have plans to modify this so that it is an actual image. It means some moving around of the markup (making sure to preserve the 100:42 aspect ratio).

If anyone wants to jump on this change, please go for it.

**Comment by rhymes** [comment] 2020-04-19 07:55
We do have a `DEV team` issue open about the switch from background image to "image image"

https://github.com/thepracticaldev/dev.to/issues/7289

**Comment by benhalpern** [comment] 2020-04-20 22:39
I can confirm that this has been fixed by https://github.com/thepracticaldev/dev.to/pull/7396

Nice stuff @juliannatetreault 🙌

**Closed by benhalpern** 2020-04-20 22:39 UTC
Labels: area: articles, ready for dev, tech: ruby, type: feature request
