### ISSUE TITLE
Strange behavior of article editor when devtools is in use (Firefox/Chrome)

### ISSUE THREAD

**Issue by abdellani** [thepracticaldev/dev.to#5970] opened 2020-02-09 04:11 UTC
**Describe the bug**

When I open the devtool under firefox and chrome, the article editor doesn't work properly. The first problem that I noticed was that the title field shrinks. Later, I discovered that when I try to preview an empty post both the preview panel and the text editor show up at the same time.

**To Reproduce**

1. Open web developper tool under Firefox/Chrome (before accessing the editor),
2. Click on `write a post`,
3. Write a title for the article `test` for example,
4. Click preview before writing any content.

**Expected behavior**

The pages should behave as if the devtool is not opened.
**Screenshots**

I recorded a short video about the problem :
![issue](https://user-images.githubusercontent.com/16113997/74095892-6d56bd00-4af7-11ea-9fb3-1e8bb901c1f0.gif)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.3 LTS
- Browser: Mozilla Firefox 
- Version: 72.0.1
- Browser: Google Chrome 
- Version:  78.0.3904.108

**Comment by andrasbacsai** [comment] 2020-02-09 12:25
I could not reproduce it.

What kind of extensions do you use? 
Could you please try the same in incognito mode or with disabled extensions?

(I see the backend.js errors in your console, which is (just a guess) vue-devtools, as it has a backend.js which I'm aware of. )

**Comment by citizen428** [comment] 2020-02-10 06:20
@abdellani Thanks for the report. However, I was also not able to reproduce this, with neither of the two editor type configurable at https://dev.to/settings/ux. Apart from what @andrasbacsai suggested, can you please also try to a hard refresh and make sure it's not some caching issue?

**Comment by abdellani** [comment] 2020-02-10 11:55
When I disabled the react extension, the problem disappeared. I'm using the version 4.4.0 in both browsers.
**Firefox**
![Screenshot from 2020-02-10 12-48-32](https://user-images.githubusercontent.com/16113997/74147569-c3188b80-4c03-11ea-8557-ef056de9f3ed.png)
**Google Chrome**
![Screenshot from 2020-02-10 12-51-16](https://user-images.githubusercontent.com/16113997/74147692-0d9a0800-4c04-11ea-8f69-5959ff8e0805.png)

**Comment by andrasbacsai** [comment] 2020-02-10 12:31
I think it's related to a [react-devtools issue](https://github.com/facebook/react/issues/16500) & probably because DEV.to using the older version of preact (8.5.3).

**Comment by rhymes** [comment] 2020-02-10 15:03
@abdellani @andrasbacsai as this is not related to our code I think it's safe for us to close it. We plan to upgrade to Preact X sometime in the future :)

**Closed by rhymes** 2020-02-10 15:03 UTC
Labels: area: publishing experience
