### ISSUE TITLE
Blank button on notifications when someone has followed you

### ISSUE THREAD

**Issue by aviskarkc10** [thepracticaldev/dev.to#8310] opened 2020-06-06 04:23 UTC
**Describe the bug**

In the notifications section, when someone has followed me, I get a blank button without any text in it.

**To Reproduce**

- Go to notifications
- Check the notification where a user has followed you.
- The button will be blank and won't have text in it.

**Expected behavior**

I am guessing there should be a text to follow the user back?

**Screenshots**

![image](https://user-images.githubusercontent.com/13309631/83935869-58581500-a7dd-11ea-9677-2c0f0a138d63.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Chrome
- Version: 80.0.3987.87

**Additional context**

N/A

**Comment by rhymes** [comment] 2020-06-07 10:41
Hi @aviskarkc10, thanks for the issue. I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/6377 and https://github.com/thepracticaldev/dev.to/issues/6616

Let me know if this is not the case

**Closed by rhymes** 2020-06-07 10:41 UTC
Labels: triage

**Comment by aviskarkc10** [comment] 2020-06-07 10:57
it is actually. didn't realize there was an issue for it already :+1:
