### ISSUE TITLE
Theme updates - Example

### ISSUE THREAD

**Issue by carlosangon** [thepracticaldev/dev.to#1413] opened 2018-12-28 05:06 UTC
**Is your feature request related to a problem? Please describe.**
Current theme can be a bit harsh on my eyes at night or even during the daytime. 

**Describe the solution you'd like**
I'd like to create a "dark-mode theme" and re-style certain elements, including font-size.

**Describe alternatives you've considered**
Editing theme each time I visit DEV.to with DevTools.

**Additional context**
A few simple updates I did with DevTools in just a few minutes.

<img width="1680" alt="screen shot 2018-12-27 at 10 54 33 pm" src="https://user-images.githubusercontent.com/2627624/50503189-b5696c00-0a2a-11e9-8827-5a9fe7a612bb.png">

@benhalpern @jessleenyc @pkfrank @maestromac @Zhao-Andy 

Thoughts?

**Comment by maestromac** [comment] 2018-12-28 19:36
Yep,  what @rhymes said, there's currently an ongoing effort to implement dark-theme.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/134 . Thanks for the issue though 😃

**Closed by maestromac** 2018-12-28 19:36 UTC
Labels: triage
