### ISSUE TITLE
Ability to exclude tags

### ISSUE THREAD

**Issue by drewswaycool** [thepracticaldev/dev.to#3246] opened 2019-06-20 16:28 UTC
I want to be able to see all #react tag posts, but not include #react #redux posts.

It would be nice to always exclude posts based on tags you don't want to see.

**Comment by maestromac** [comment] 2019-06-25 19:26
Thank you for this issue! A similar issue already exist. You are welcome and encourage to continue the conversation there.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/1856

**Closed by maestromac** 2019-06-25 19:26 UTC
Labels: feature request
