### ISSUE TITLE
Reloading too much gives an unrelated page

### ISSUE THREAD

**Issue by belhassen07** [thepracticaldev/dev.to#1953] opened 2019-03-03 12:33 UTC
I reloaded the home page multiple times, 6-7 clicks in a 1s. What I got is this page
![annotation 2019-03-03 132940](https://user-images.githubusercontent.com/22170583/53695213-bc10b880-3db8-11e9-94d7-7fffb4b09b0b.jpg). Which is the same screen you get when making an empty search. I thought I should report this.

**Comment by Zhao-Andy** [comment] 2019-03-05 15:23
Thanks for the report. This is a duplicate of https://github.com/thepracticaldev/dev.to/issues/1206, so we'll keep that one open instead.

**Closed by Zhao-Andy** 2019-03-05 15:23 UTC
Labels: triage
