### ISSUE TITLE
Twitter Social Card for Comments Doesn't Display Properly 

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#3296] opened 2019-06-24 13:38 UTC
A user wrote in explaining that when trying to share a comment on Twitter, the social card doesn't display properly. They provided reasons as to why they think it's happening. :

![https://cl.ly/8996514f2ccc/Image%202019-06-24%20at%209.35.34%20AM.png](https://cl.ly/8996514f2ccc/Image%202019-06-24%20at%209.35.34%20AM.png)

To repeat:
1. Copy the link to a comment - https://dev.to/codedgar/comment/c9fk
2. Drop it in the card validator - [https://cards-dev.twitter.com/validator](https://cards-dev.twitter.com/validator)

**Comment by maestromac** [comment] 2019-06-25 20:08
Thanks for this issue. Ideally the social card for a comment should display a preview of comment itself instead of the article's title. 

Anyone who wishes to grab this issue should take a look at @mscoutermarsh 's [awesome works](https://github.com/thepracticaldev/dev.to/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amscoutermarsh+) using [HCTI](https://htmlcsstoimage.com/).

**Comment by jessleenyc** [comment] 2019-08-08 00:52
Yep, once you get the image working you'll want to update the meta info on the comment show page with the updated image.

**Comment by blunket** [comment] 2019-10-01 20:03
@maestromac I'd like to help with this if I can, but I'm not sure I am fully understanding what needs to be done with the card image. What should the card's image look like?

**Comment by ektaarora3501** [comment] 2019-11-17 11:48
Hi , I am a new contributor  and want to help with this issue ..

**Comment by brobertsaz** [comment] 2020-03-05 01:16
@jessleenyc Is this still open issue?  Looks like @ektaarora3501 might have volunteered already.

**Comment by Oghenebrume50** [comment] 2020-06-17 12:14
@jessleenyc @rhymes can I work on this, if yes, I would need more context on what exactly this issue address because I tried pasting a GitHub comment link into the twitter card and I got the exact same type of card as the OP posted in his own screenshot like you can see below.  

isn't the problem how the card is displayed? from my observation the comment preview shows fine wish is @maestromac first pointer, then the next will be the image display but this is exactly how Github's comments show too when previewed

![checkissue](https://user-images.githubusercontent.com/37092867/84896140-51fa5080-b09b-11ea-8cd3-a187ca31994c.png)

**Comment by nickytonline** [comment] 2020-06-17 12:38
@rhymes, it might be that for comments we just display the card differently because I'm able to generate one for a comment like above using the original comment link mentioned in the inital issue comment.

![image](https://user-images.githubusercontent.com/833231/84898789-cb7f4800-b075-11ea-96c0-2ab3fb1129d0.png)

@maestromac, do you know if for comments the social card looks different compare to a post social card?

**Comment by maestromac** [comment] 2020-06-17 15:17
This is what the social card looks like when it's an article
![image](https://user-images.githubusercontent.com/15793250/84916349-fa081d80-b08b-11ea-8d12-d0a77d9689e0.png)

And this is what it looks when it's a comment
![image](https://user-images.githubusercontent.com/15793250/84916196-c0cfad80-b08b-11ea-8d0a-5fa39fe46605.png)
We don't want that. We would like the custom image we generated to take up most of the space like it is for articles. We want them to be in an identical format.

**Comment by Oghenebrume50** [comment] 2020-06-17 17:20
Got it

**Comment by nickytonline** [comment] 2020-06-17 18:56
Since you wanted to work on the @Oghenebrume50, I will assign it to you.

**Comment by Oghenebrume50** [comment] 2020-06-19 17:23
hi @maestromac @nickytonline so I have been trying to work on this and basically I cannot reproduce the bug locally because the twitter validator does not catch images from my local build even when I use a public interface like Ngrok.
So in the screenshot below, I did put in an article link to the twitter validator but it doesn't catch the image, is there something I am missing for my local environment that would make this happen?  

![ngrokfastly](https://user-images.githubusercontent.com/37092867/85162629-9895a980-b259-11ea-9f44-936ea6d9d840.png)

I would appreciate any pointer because with this I cannot know what works and what doesn't work.

**Comment by maestromac** [comment] 2020-06-22 14:58
@Oghenebrume50 this might be because you don't have HCTI's API locally so the feature may have been disabled. You'll need to sign up and obtain your own personal API key from [HCTI](https://htmlcsstoimage.com/) and give it another try

**Closed** 2020-06-23 17:03 UTC
Labels: future, good first issue, hacktoberfest, ready for dev, tech: html/css, tech: ruby, type: bug
