### ISSUE TITLE
Posts on front page do not load until scrolled down

### ISSUE THREAD

**Issue by Zhao-Andy** [thepracticaldev/dev.to#1805] opened 2019-02-14 18:35 UTC
When going to the home page, sometimes posts under the first post do not load until you scroll down. The page simply hangs and looks like this:
![image 1](https://user-images.githubusercontent.com/17884966/52808675-6f10b080-305c-11e9-88d5-dd69c5beef6a.png)

This seems to happen on Windows 10, Chrome. Possibly related extension is uBlock Origin.

I think that we load the posts with Algolia, so there might be some JS that is triggered by scrolling. Not 100% sure though.

**Comment by maestromac** [comment] 2019-02-15 16:13
Is this difficult to reproducible?

**Comment by kspeakman** [comment] 2019-03-08 16:28
I can observe this right now on the website. Whenever I am at the top of the page and I hit refresh, this is what I see.

![image](https://user-images.githubusercontent.com/4582668/54040712-a53cde00-418b-11e9-848e-7c8a05453a5b.png)

The articles finally load when the last item in the "#shecoded" section scrolls into view. This is what it looks like just before I get to the last item.

![image](https://user-images.githubusercontent.com/4582668/54041283-ec779e80-418c-11e9-89ff-d6e7f3299cc9.png)

And this is what it looks like once the last item scrolls into view.

![image](https://user-images.githubusercontent.com/4582668/54041150-9a367d80-418c-11e9-86bb-cdce9c5866cf.png)

**Comment by jessleenyc** [comment] 2019-08-01 01:45
@kspeakman have you continued to experience this?

**Comment by kspeakman** [comment] 2019-08-01 02:09
@jessleenyc Oh yes, every day. Here is what I see when scrolled to the top and hitting refresh right now.

![image](https://user-images.githubusercontent.com/4582668/62260090-64fa2880-b3d6-11e9-93f5-1632bf81bb86.png)

If I scroll down far enough, it will load the other articles. In the pic below, the very next scroll click down will load the articles.

![image](https://user-images.githubusercontent.com/4582668/62260198-c28e7500-b3d6-11e9-8399-ea83c9ad451b.png)

This happens across Brave, Chrome, Firefox. **This only appears to happen when I am logged in.** When I am signed out, I never see the loading behavior... the articles are just there immediately.

**Comment by jessleenyc** [comment] 2019-08-07 22:39
That is so strange. Are you using any notable extensions across all three browsers?

**Comment by kspeakman** [comment] 2019-08-07 23:28
I'm using both Privacy Badger and uBlock Origin. However, with both turned off (disabled in Extensions in Chrome) I still see the same behavior. 

![image](https://user-images.githubusercontent.com/4582668/62664347-ec98e780-b940-11e9-9913-aaf8b39f351c.png)

When I change the browser width to below 1120px, where the right column is gone, then it loads immediately.

![image](https://user-images.githubusercontent.com/4582668/62664400-09cdb600-b941-11e9-8c0b-197c371ed135.png)

**Comment by jessleenyc** [comment] 2019-08-08 03:17
Very Interesting. Planning to bring this up with the team at our next tech meeting.

**Comment by dzhavat** [comment] 2019-08-11 06:37
I experience this as well on Firefox. Actually came here to open an issue and founds this one. Usually the problem occurs for me right after logging in with GitHub. To fix it I either refresh the page or scroll a bit down.

**Comment by rohitshetty** [comment] 2019-08-22 02:42
I can experience this as well with Firefox on linux, each time I goto dev.to.

**Comment by rohitshetty** [comment] 2019-08-29 22:52
@jessleenyc @benhalpern If this is not a high priority and immediate fix can I take this up to investigate further and raise a PR if possible?

**Comment by jessleenyc** [comment] 2019-09-04 19:04
@rohitshetty, please go for it!! We've tried looking at it last week but it's a bit trickier than we realized so additional eyes are much appreciated.

**Comment by rohitshetty** [comment] 2019-09-26 11:14
I just replicated this on a friends laptop. The list loads alright when he is not logged in, but does not load when he is signed in. Looking into it further

**Comment by colbymelvin** [comment] 2019-10-04 21:23
I am experiencing this on the dev.to website in both Chrome and Firefox. I can also easily reproduce this in master on my local machine.

This is caused by the code in `app/assets/javascripts/initializers/initScrolling.js.erb#fetchNextPageIfNearBottom`.

When the content in  `app/views/articles/tags/_sidebar_additional.html.erb` exceeds a certain threshold, it impacts `document.documentElement.scrollHeight` and therefore the scroll calculation.

@rohitshetty , I have a working fix for this and would like to submit a PR this weekend if that's alright! Not sure if you were still looking into this.

**Comment by rohitshetty** [comment] 2019-10-04 22:13
@colbymelvin Sure! I had guessed the problem to be in initScrolling too, but have been busy last few weeks with work and couldn't test it locally. 
Thank you for the fix, please feel free to submit the PR :)

**Comment by jessleenyc** [comment] 2019-10-08 20:59
Some more reports/info here: https://github.com/thepracticaldev/dev.to/issues/4242

**Comment by jessleenyc** [comment] 2019-10-08 21:01
Also made a post about this: https://dev.to/jess/call-for-dev-contributors-posts-on-front-page-do-not-load-until-scrolled-down-5e6a

**Comment by rohitshetty** [comment] 2019-10-08 21:43
Hey @colbymelvin are you still working on this?

**Comment by colbymelvin** [comment] 2019-10-08 21:45
@rohitshetty @jessleenyc I submitted a PR for this here: https://github.com/thepracticaldev/dev.to/pull/4279

**Comment by rohitshetty** [comment] 2019-10-08 21:46
@colbymelvin Awesome! Thank you

**Comment by kvharish** [comment] 2019-10-09 11:29
I raised the same issue here [4314](https://github.com/thepracticaldev/dev.to/issues/4314). I have closed it now. Good to see that it's fixed. Thanks, @colbymelvin.

**Comment by kvharish** [comment] 2019-10-13 04:32
Hi, @colbymelvin @jessleenyc The issue is fixed now.

**Comment by DonkeyKongJr** [comment] 2019-10-14 13:22
I raised it as well in #4408 and closed it. Happy to see that there is already a PR @colbymelvin. 
Thanks

**Comment by mike-healy** [comment] 2019-10-16 01:45
If the PR happens to be unsuitable for whatever reason, could the articles not just be loaded on initial page load? Is there a benefit to waiting for a scroll action?

**Comment by colbymelvin** [comment] 2019-10-16 17:15
@mike-healy I had the same thought. I do think it would make sense to fetch the first "page" of articles/videos/podcasts on initial page load, but felt more comfortable just fixing the existing scroll logic bug in #4279 . 

I'm happy to make that change in the PR if the reviewer requests it, but maybe it makes more sense to submit an additional PR to refactor the fetching logic?

**Closed** 2019-10-18 20:41 UTC
Labels: help wanted, type: bug
