### ISSUE TITLE
Ability to filter posts in the dashboard

### ISSUE THREAD

**Issue by theoutlander** [thepracticaldev/dev.to#889] opened 2018-10-11 20:34 UTC
**Is your feature request related to a problem? Please describe.**
I pull my articles via the RSS feed on Medium. One of the annoying things about Medium is how it treats comments as posts. A side effect of this is that the list of posts on the dashboard is cluttered with lots of comments.

**Describe the solution you'd like**
I would like the ability to filter posts by:

- Published
- Drafts

**Describe alternatives you've considered**
Currently, there's no way to filter the list or ignore specific items.

**Additional context**
I don't think there's a user-friendly way to ignore a post. So, we may want to consider a feature where we can delete a specific post that's pulled in via RSS. Although, what if someone wants to undelete a specific post because they accidentally deleted it? Perhaps the next best option is to be able to filter by published and drafts.

**Comment by pkfrank** [comment] 2018-10-11 21:02
Hey @theoutlander, thanks for the issue.  I can definitely see why this would be useful, especially as you rack up more articles / drafts.  I imagine @benhalpern will jump in with some additional thoughts.

**Comment by Turnerj** [comment] 2019-04-09 08:28
I've been thinking the same thing recently as I start a draft for one post but not finish it for months, now it appears between all the published posts I have done. Even if posts were sorted so drafts were first (in created order) and published posts were sorted by published date, it would help a lot. 🙂

**Comment by jessleenyc** [comment] 2019-08-07 20:42
I think you probably know this already (maybe you even helped work on it?!) but we can sort articles on the dashboard by published which brings all unpublished posts to the top and then sorts by published date. Perhaps that will help until we get a filter in.

**Comment by jessleenyc** [comment] 2019-08-07 23:15
Just realized there is a duplicate of this issue that is newer with some additional implementation suggestions, so I'm going to close this one in favor of https://github.com/thepracticaldev/dev.to/issues/2351

**Closed by jessleenyc** 2019-08-07 23:15 UTC
Labels: area: publishing experience, help wanted, type: feature request
