### ISSUE TITLE
Cannot load some articles

### ISSUE THREAD

**Issue by Cry0nicS** [thepracticaldev/dev.to#5245] opened 2019-12-25 10:10 UTC
While searching for some specific topics I stumbled upon a bunch of posts that cannot be open. They get stuck at _loading_.

Not much to reproduce, just click one of the following links:

- https://dev.to/acro5piano/5-reasons-why-git-based-resume-is-awesome-127

- https://dev.to/agazaboklicka/how-to-write-a-solid-dev-resume-to-be-2018-star-3h8a

In search results, these articles are displayed correctly tho.
![image](https://user-images.githubusercontent.com/29982205/71442670-a08fe900-270f-11ea-8ae1-0e76d88d26e9.png)

**Comment by rhymes** [comment] 2019-12-26 09:58
Can you try again because by clicking on those two links I can't reproduce the problem. I also checked the dev console but I don't see anything weird :)

**Comment by Cry0nicS** [comment] 2019-12-26 17:37
@rhymes thanks for your reply. I tried with Chrome, Vivaldi and Brave. None of them opened the above URLs (any other URL loaded perfectly).

![image](https://user-images.githubusercontent.com/29982205/71484859-35c9d500-2817-11ea-8662-94b563300f3b.png)

**Comment by rhymes** [comment] 2020-01-21 15:59
Hi @Cry0nicS, sorry for the delay, I'm sorry I've missed the reply for all this time.

Have you found a solution? Is still happening?

**Comment by maestromac** [comment] 2020-02-14 23:37
This was a temporary hiccup during our app shell model migration. It should no longer be an issue but please let us know right away if any link is acting up. 

Closing.

**Closed by maestromac** 2020-02-14 23:37 UTC
Labels: type: bug
