### ISSUE TITLE
wierd ui to upload images in comments and it then throws them away

### ISSUE THREAD

**Issue by osde8info** [thepracticaldev/dev.to#5571] opened 2020-01-18 16:05 UTC
**Describe the bug**

wierd UI for upload image in a comment and nothing happens
**To Reproduce**

create a comment
click add image
get a wierd url with dots around it
save
nothing happens

**Expected behavior**

image should be saved in comment

**Screenshots**

https://res.cloudinary.com/osde8info/image/upload/v1579363486/Screenshot_2020-01-18_JetBrains_Mono_A_free_and_open_source_typeface_for_developers_-_DEV_Community_kowpfp.png

**Desktop (please complete the following information):**

- OS: xubuntu 18
- Browser: ff 72
- Version: latest

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

https://res.cloudinary.com/osde8info/image/upload/v1579363486/Screenshot_2020-01-18_JetBrains_Mono_A_free_and_open_source_typeface_for_developers_-_DEV_Community_kowpfp.png

**Comment by rhymes** [comment] 2020-01-18 16:27
Hi @osde8info, this is not strictly a bug, the comments editor requires markdown, when up load an image you will get the URL of such image that you then have to copy and paste in the editor using the markdown tags for inline images (see "inline images" in the editor guide):

So for example, if I wanted to inline your screenshot up here I would do this:

```markdown
![comment editor](URL)
```

which results in:

![comment editor](https://res.cloudinary.com/osde8info/image/upload/v1579363486/Screenshot_2020-01-18_JetBrains_Mono_A_free_and_open_source_typeface_for_developers_-_DEV_Community_kowpfp.png)

If you wish that to be changed you can submit a feature request with the description of the feature you wish implemented.

You might be interested in subscribing or contributing thoughts to these two issues:

- [bulk upload or drag and drop](https://github.com/thepracticaldev/dev.to/issues/4126)
- [inline markdown cheatsheet](https://github.com/thepracticaldev/dev.to/issues/49)

In the meantime I'm going to close this as it's not a bug.

Let me know if you have further questions!

**Closed by rhymes** 2020-01-18 16:27 UTC
Labels: triage
