### ISSUE TITLE
Issue with deleting articles auto-imported through RSS

### ISSUE THREAD

**Issue by achasveachas** [thepracticaldev/dev.to#175] opened 2018-03-12 01:39 UTC
# _BUG_
### Current Behavior
When an article gets imported automatically from my RSS feed I can't delete it from my dashboard.

When I try it initially gets deleted, but then after some time it gets re-imported from my RSS feed again.

### Expected Behavior
When an article is imported once it should not be imported again, even if it is not in the dashboard anymore.

### Additional Info (steps to replicate, device/browser, helpful links)
Steps to replicate:
1. Set up an account to auto import an RSS feed.
2. Wait until an article gets imported.
3. Delete it.
4. Wait for it...
5. It's right back in the Dashboard.

**Comment by Zhao-Andy** [comment] 2018-03-12 14:55
Hey @achasveachas, thanks for the heads up. Going to close this one since it's a duplicate of #137, although your issue summarizes the thread of #137. 👍

**Closed by Zhao-Andy** 2018-03-12 14:55 UTC

**Comment by achasveachas** [comment] 2018-03-12 15:04
Sorry about that, I tried searching for the issue, guess I missed it. Glad it's being worked on.

**Comment by kievsash** [comment] 2019-06-26 08:04
+1 Still observing this issue
