### ISSUE TITLE
Printing issues with Chrome

### ISSUE THREAD

**Issue by gabrieleromanato** [thepracticaldev/dev.to#5429] opened 2020-01-10 05:19 UTC
Hi! This is just to inform you that at the moment printing your articles as PDF is not possible (see shot). You should add a CSS for print. 
<img width="380" alt="1dbk0wGV" src="https://user-images.githubusercontent.com/1553348/72127849-2d25e280-3371-11ea-942b-6f761b3378e3.png">

**Comment by renatamarques97** [comment] 2020-01-10 14:46
Hey @gabrieleromanato, can you provide reproduction steps? I execute Ctrl + P for printing and it seems okay to me.

**Comment by rhymes** [comment] 2020-01-10 15:53
@gabrieleromanato can you also please add what browser and operating system you're using? Thank you!

**Comment by gabrieleromanato** [comment] 2020-01-13 07:34
macOS Catalina 10.15.2
iMac (Retina 5K, 27-inch, Late 2015)
Google Chrome Version 79.0.3945.117

**Comment by renatamarques97** [comment] 2020-01-18 19:36
@gabrieleromanato I have the same settings as you, and I still can't reproduce the error.

**Comment by maestromac** [comment] 2020-01-23 22:53
@gabrieleromanato can you please provide us the link to that article you were trying to print?

**Comment by Amorpheuz** [comment] 2020-01-30 17:25
https://dev.to/macmacky/70-javascript-interview-questions-5gfi I think this is the one! Might have to with the size of the print? (111 Pages 😲)... It took a decent amount of time for me but did end up correctly rendering!
![image](https://user-images.githubusercontent.com/22113778/73473454-d1200e00-43b2-11ea-80cf-1cf8db32f736.png)
![image](https://user-images.githubusercontent.com/22113778/73473733-44c21b00-43b3-11ea-81bd-d824ac692797.png)

**Specifications**
Windows 10 Home
Google Chrome Version 79.0.3945.130

**Comment by yogeshktm** [comment] 2020-02-10 11:11
Same page renders fine in **Windows 8** - **Chrome** Version **79**.0.3945.130 (Official Build) (64-bit)

<img width="947" alt="chrome" src="https://user-images.githubusercontent.com/3961774/74145152-274b4780-4c24-11ea-8493-fff5dc4e5c55.png">

**Comment by maestromac** [comment] 2020-02-10 21:38
I too was unable to reproduce this error. My wild guess is this could be specific to your machine's font settings @gabrieleromanato

**Comment by maestromac** [comment] 2020-02-17 14:06
Seeing that this most likely isn't an issue anymore, I'm closing the issue. Please do let us know this issue persist!

**Closed by maestromac** 2020-02-17 14:06 UTC
Labels: tech: html/css, type: bug
