### ISSUE TITLE
Dashboard: Total Post Views does not correctly indicate the sum of all articles views

### ISSUE THREAD

**Issue by pacoita** [thepracticaldev/dev.to#3723] opened 2019-08-15 09:33 UTC
**Describe the bug**
The `TotalViews` value in the dashboard page does not represent the correct sum of each article views.

In my case:
```
    // Yesterday
    "date": "2019-08-14T15:15:41"
    "totalViews": "4,840"

    // Today
    "date": "2019-08-15T07:16:13",
    "totalViews": "4,926",
```
Since yesterday the only views change was related to a new article with 129 views. Therefore the total views result should be: `4,840 + 129 = 4,929` and not 4,926.

Is there any delay in updating the total views sum?

**To Reproduce**
Analyse two articles at a distance of one day and check the total views value with the sum of all individual articles views.  

**Expected behavior**
The TotalViews amount should be the sum of all individual views or higher (in case some articles have "under 100" label)

- OS: iOS Mojave 10.14.6
- Browser: Chrome
- Version: 76.0.3809.100

**Comment by rhymes** [comment] 2019-08-15 13:04
Hi @pacoita, I thought it was some JSON API we forgot about, but you're talking about the box "Total Post Views" in https://dev.to/dashboard  right?

That value is the sum of all `page_views_count` for each article:

https://github.com/thepracticaldev/dev.to/blob/0f46b0deededb0ca7602b6d14dbb2b464f76a160/app/views/dashboards/_analytics.html.erb#L1-L2

Such value is not updated constantly, but sampled for each article. Hence the reason why it's not a precise count:

https://github.com/thepracticaldev/dev.to/blob/0f46b0deededb0ca7602b6d14dbb2b464f76a160/app/controllers/page_views_controller.rb#L30-L38

I've updated the title to clarify what the issue is about

**Comment by pacoita** [comment] 2019-08-15 13:07
Yes, the total views is the central box in the dashboard page.

So the total views value is updated live, then it should be just a matter of time before the values are correct again. Thanks

**Comment by jessleenyc** [comment] 2019-08-15 15:46
Since this is fairly expected behavior, I'm going to close this issue.

**Closed by jessleenyc** 2019-08-15 15:46 UTC
Labels: triage
