### ISSUE TITLE
Feature Request for the Reading list

### ISSUE THREAD

**Issue by ezio1404** [thepracticaldev/dev.to#8411] opened 2020-06-11 16:06 UTC
Good day Devs,
**Is your feature request related to a problem? Please describe.**
I like the post and contents in dev.to but I want to read it without internet, so I save it to the reading list. As my reading list grow I cannot download them all in one time. Because not all have an Internet access(like me). 

I'm frustrated when I download them one at a time it cosumes more effort and time.

**Describe the solution you'd like**

I would like to suggest that there is an option that you can download them all in batch and by selected filters.

**Describe alternatives you've considered**

Feature 1 : Download all Post Content with comments 
Feature 2:  Download only Post Content

**Additional context**

**Comment by rhymes** [comment] 2020-06-11 16:13
Hi @ezio1404, I'm closing this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/5692 - please add your comment there as well so we can keep track of it more easily.

Thank you!

**Closed by rhymes** 2020-06-11 16:13 UTC
Labels: area: reading list, tech: fullstack
