### ISSUE TITLE
Built in cover image photo credit

### ISSUE THREAD

**Issue by desirottman** [thepracticaldev/dev.to#2131] opened 2019-03-20 18:58 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm writing a post, and I'm not sure how to format photo credits.

**Describe the solution you'd like**
It would be nice if there was a markdown tag in the post editor to attribute a stock photo to its source, or if the content included in the "new post" included a prepopulated, formatted spot to add attribution.

**Describe alternatives you've considered**
Right now I enter it as an italicized text link, but then it's the same size as the post content and doesn't look as nice as it could if it was consistent across all posts.

**Additional context**
Maybe it could be something like this: 
![image](https://user-images.githubusercontent.com/11390786/54711373-c2709580-4b17-11e9-90de-ce905e34fa17.png)

Or as a suggested formatting in the help section:
![image](https://user-images.githubusercontent.com/11390786/54711549-30b55800-4b18-11e9-8d93-29746da3ec5a.png)

**Comment by abraham** [comment] 2019-03-20 19:05
Looks like a duplicate of #1849.

**Comment by Zhao-Andy** [comment] 2019-03-20 19:06
Hey @desirottman, thanks for the issue! We actually have an open issue for this via #1849. It'd be great if you could leave a comment in #1849 with your screenshots.

**Closed by Zhao-Andy** 2019-03-20 19:06 UTC
Labels: triage
