### ISSUE TITLE
Revision history of articles

### ISSUE THREAD

**Issue by TomoyukiAota** [thepracticaldev/dev.to#4832] opened 2019-11-15 16:24 UTC
**Is your feature request related to a problem? Please describe.**

I encountered a situation that an older version of my article appeared on the editor page. The problem is resolved after deleting the browser cache. (Chrome's hard to reload did not resolve this problem.) It was frustrating because it seemed like the article is really reverted somehow at first sight. If I had a revision history, I would have been sure that that the content in the server is correct and it is not loaded on the browser.

**Describe the solution you'd like**

I would like to have a revision history page just like Wikipedia.
https://en.wikipedia.org/w/index.php?title=Main_Page&action=history

**Describe alternatives you've considered**

Users can manage article versions locally on their PC by Git and copy&paste the latest content on Dev.to, but this is not convenient.

**Additional context**

Tracking revision history is necessary to collaboratively edit the same article by multiple users. Having this feature opens the possibility of features like "edit request" which readers can send requests for edit just like the pull request in GitHub.

**Comment by jessleenyc** [comment] 2019-11-18 15:05
Sorry for the frustrating experience. We do want to support version history for articles and are open to suggestions here. There's some discussion on this issue, which is a request for versioning on our static pages: https://github.com/thepracticaldev/dev.to/issues/2836

**Comment by TomoyukiAota** [comment] 2019-11-18 16:34
@jessleenyc Thanks, #2836 is the feature I want.

**Comment by maestromac** [comment] 2019-11-21 20:48
Closing this because it is a duplicate of https://github.com/thepracticaldev/dev.to/issues/2836. Please kindly continue the conversation on that issue.

**Closed by maestromac** 2019-11-21 20:48 UTC
Labels: type: discussion, type: feature request
