### ISSUE TITLE
Add an ovelay ImageViewer while clicking embed images in a post

### ISSUE THREAD

**Issue by anandhumanoj** [thepracticaldev/dev.to#705] opened 2018-09-20 14:17 UTC
## Feature Request or Task

Task 1: Implement an image viewer to Watch, Zoom in-out and Link to the image etc. for embed images in the post instead of *&lt;a&gt;* link to that image

### User Story / Description

First of all, I am very happy with how __dev.to__ is today. 
Task1: Suppose, I'd like to view images inside a post in enlarged form. Currently, when an image is clicked I get a link to the image which kicks me out of dev.to space, which is, __Annoying__ at least for me. 

### Definition of Done

When I click an image inside a post, I could see an overlay( or something better ) with the respective image. The preview could also include a zoom in-out button and link to the image etc..

**Comment by jessleenyc** [comment] 2018-10-04 16:21
Thanks for the request @anandhumanoj. Closing this issue because it's a duplicate of #413.

**Closed by jessleenyc** 2018-10-04 16:21 UTC

**Comment by anandhumanoj** [comment] 2018-10-04 19:04
Really sorry that I made a duplicate request. Thanks for the response
