### ISSUE TITLE
Login seems to be broken again.

### ISSUE THREAD

**Issue by hwolfe71** [thepracticaldev/dev.to#4242] opened 2019-10-05 05:16 UTC
The main page is broken again, like issues #2919, #3081, #2790, #2983. It is not loading completely and only notifications will load properly. The connect page, my reading list and listings pages do not full load either, and the profile link is not clickable. I have cleared cookies twice and tried logging in via both github and twitter, with the same results.

See attached screenshot of the main page.

![dev to_screenshot_1005](https://user-images.githubusercontent.com/5009118/66250096-75df5700-e703-11e9-8249-6e6136726d12.png)

- OS: Linux - PCLinuxOS
- Browser: Pale Moon
- Version: 28.6.1

uBlock Origin and AdBlock Latitude are both installed, but disabled on dev.to.

**Comment by MythreyaK** [comment] 2019-10-05 18:04
Same here! Site is unusable at all. Mobile site still works OK. Some concerning errors in the console window. 

![image](https://user-images.githubusercontent.com/26112391/66258920-83aae000-e7c8-11e9-97f3-03827ca0e92f.png)

**Comment by jessleenyc** [comment] 2019-10-08 20:36
Thanks for reporting this -- I'm going to close this issue since it seems like a duplicate of #1805. Sorry you're experiencing this - we've been trying to figure out.

**Closed by jessleenyc** 2019-10-08 20:36 UTC
Labels: type: bug

**Comment by MythreyaK** [comment] 2019-10-31 09:23
Hmm that issue seems a bit different as nothing loads even if I scroll all the way down. The footer is broken, I can't open my account either (by clicking the profile icon).
