### ISSUE TITLE
Move "Images" button from text bottom to buttons panel

### ISSUE THREAD

**Issue by rumkin** [thepracticaldev/dev.to#4064] opened 2019-09-19 09:39 UTC
### Problem

Image upload dialog button is located after the textarea element in the editor. Insertion of an article cover or other images makes user to scroll to the page bottom, upload image and then scroll back to the position where image should be placed.

Why it's bad: users loose context after image upload and need to spend some time to restore it. And as result it require more author's attention and take it from spell and other checks.

### Solution

Move the "IMAGES" button into buttons panel (`.articleform__buttons`). It could be placed right after the help button.

<img width="450" alt="Screen Shot 2019-09-19 at 12 01 05" src="https://user-images.githubusercontent.com/609373/65230660-e9178500-dad6-11e9-9fff-17a709eeaaa6.png">

### Context

Scrolling position should remain the same after upload dialog is closed.

**Comment by maestromac** [comment] 2019-09-20 14:37
Thank you for this suggestion @rumkin ! There already an issue on this. Please continue the conversation there.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/2994

**Closed by maestromac** 2019-09-20 14:37 UTC
Labels: triage
