### ISSUE TITLE
Add web push notifications :3

### ISSUE THREAD

**Issue by marataziat** [thepracticaldev/dev.to#1020] opened 2018-10-29 03:35 UTC
**Is your feature request related to a problem? Please describe.**
Web push notifications for new posts

**Comment by jessleenyc** [comment] 2018-10-30 21:09
Thanks for the issue @marataziat! Looks like it's a duplicate of https://github.com/thepracticaldev/dev.to/issues/997 so I'm going to close this one. Definitely encourage you to upvote the other one if this is a feature you're interested in :)

**Closed by jessleenyc** 2018-10-30 21:09 UTC
Labels: triage
