### ISSUE TITLE
Featured repos don't support emojis 

### ISSUE THREAD

**Issue by Eros** [thepracticaldev/dev.to#612] opened 2018-09-06 16:29 UTC
### Current Behavior
The description of the bug displays as normal, however anything with an emoji displays as the text
### Expected Behavior
Displays them pretty emojis
### Mobile & Desktop Screenshots/Recordings
https://imgur.com/a/RCwisRo
emoji list https://gist.github.com/rxaviers/7360908
### Additional Info (device/browser, helpful links)
All

**Comment by maestromac** [comment] 2018-09-06 19:43
Thanks for this issue, @Eros . This looks like a duplicate of #238 .

Closing

**Closed by maestromac** 2018-09-06 19:43 UTC
