### ISSUE TITLE
Embedded videos do not work in Firefox

### ISSUE THREAD

**Issue by buntine** [thepracticaldev/dev.to#159] opened 2018-02-07 03:44 UTC
# _BUG_
### Current Behavior

Embedded videos (such as: https://dev.to/vaidehijoshi/linked-lists--basecs-video-series--2le8) do not play correctly in Firefox. 

It seems the entire video is buffered before any playback begins. This took about 3 minutes on my not-so-amazing Australian Internet connection.

It appeared entirely broken during the loading process.

### Expected Behavior

Videos should play as per Chrome, with minimal buffering.

### Additional Info (steps to replicate, device/browser, helpful links)

1) Open Firefox
2) Go to https://dev.to/vaidehijoshi/linked-lists--basecs-video-series--2le8
3) Press play

**Comment by Zhao-Andy** [comment] 2018-02-07 21:16
Hey @buntine, thanks for the feedback. I can't reproduce on my end. Did you get any error message?

**Comment by Zhao-Andy** [comment] 2018-02-14 18:20
Hey @buntine, we're thinking it was a one-off incident with our video service. Going to close this since it works for most people on Firefox. Feel free to reopen if otherwise though.

**Closed by Zhao-Andy** 2018-02-14 18:20 UTC
Labels: bug

**Comment by buntine** [comment] 2018-02-17 02:05
Sorry for the delay - yes, I can no longer replicate the issue. :)

**Comment by NirvanaFlame** [comment] 2019-06-18 07:28
Hey, I have the same problem on my firefox browser:
Firefox version: 67.0.2 (64-bit)
OS: Ubuntu 18.04
 
This video file cannot be played. (Error Code: 102630)

![image](https://user-images.githubusercontent.com/28052936/59661411-6c150080-91b3-11e9-9242-0dbe63c9ff92.png)

**Comment by maestromac** [comment] 2019-06-18 14:35
Thanks for the report @NirvanaFlame . I just tried and  wasn't able to replicate the same error on that video. Can you replicate the error in incognito mode?

**Comment by NirvanaFlame** [comment] 2019-06-18 16:37
Hey @maestromac, I will try it tomorrow. 
FYI. No problems with my home laptop.
Version:  67.2.2(64-bit)
Mozilla Firefox for Manjaro Linux
