### ISSUE TITLE
add reading history list 

### ISSUE THREAD

**Issue by KateWang2016** [thepracticaldev/dev.to#2120] opened 2019-03-20 05:35 UTC
**Is your feature request related to a problem? Please describe.**
It seems that I couldn't find the article I read before. 

**Describe the solution you'd like**
ps. add reading history list or if you already have this feature, make it more visible.
I mean the articles I clicked, not the ones I intentionally put into something like "reading later".

Thanks.

**Comment by maestromac** [comment] 2019-03-20 18:35
Thank you for your feature request @KateWang2016 . Closing this since it has been brought up before.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/1173

**Closed by maestromac** 2019-03-20 18:35 UTC
Labels: triage
