### ISSUE TITLE
change image preview

### ISSUE THREAD

**Issue by decadef20** [thepracticaldev/dev.to#3256] opened 2019-06-21 11:02 UTC
**Is your feature request related to a problem? Please describe.**

When clicking an image to preview, it will redirect to the image URL, The article is lost. We have to click the back button.

**Describe the solution you'd like**

add a previewer to handle image, like modal or something else

**Comment by rhymes** [comment] 2019-06-21 11:12
Hi @decadef20, thanks for taking the time. 

I'm going to close this as a duplicate of an older ticket https://github.com/thepracticaldev/dev.to/issues/413

**Closed by rhymes** 2019-06-21 11:12 UTC
Labels: triage
