### ISSUE TITLE
Login not working in Firefox

### ISSUE THREAD

**Issue by dmoney** [thepracticaldev/dev.to#162] opened 2018-02-15 06:24 UTC
# _BUG_
### Current Behavior
1. Click a thing that requires login (e.g., try to type in a reply field).
2. Log in using... window pops up
3. Click Twitter (or Github, doesn't matter)
4. Nothing happens. Login window stays there.

### Expected Behavior
Step 4: Logging in happens.

### Additional Info (steps to replicate, device/browser, helpful links)
* Works in: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
* Breaks in: Firefox Quantum 58.0.1 (64-bit)
* OS: macOS El Capitan 10.11.6 (15G19009)

**Comment by Zhao-Andy** [comment] 2018-02-16 15:23
Hey @dmoney, seems to work for me on Firefox. Do you have any extensions or blockers?

Also, does logging in via the navbar or the notifications page work?

**Comment by dmoney** [comment] 2018-02-16 17:27
@Zhao-Andy Hi Andy,  no extensions.  I did enable tracking protection in Firefox's Privacy & Security settings, but I don't see the icon by the address bar indicating there's any being blocked on dev.to.  Signing in by notifications doesn't work, but the icon next to notifications (looks like nine squares) did just let me sign in via Twitter.

**Comment by Zhao-Andy** [comment] 2018-02-16 17:47
Alright, glad you got to sign in at least. I still can't reproduce unfortunatelyIf you'd like, could you try to sign in again and have your browser dev console open? Let me know if you see any errors.

We have a few different places where you can sign in. Up to you if you want to test them all:
1. Navbar menu sign-in
2. Notifications
3. Home page, top right widget
4. Home page, a little below the feed
5. Interacting with something (modal show up)

Also, we currently have two different modals that show up when you try to sign in by interacting with something. Do you happen to remember which one you saw?

**Comment by dmoney** [comment] 2018-02-16 21:03
Apparently I was wrong about trackers being blocked.  I was looking for a different icon, and if I disable tracking protection, things seem to work.  
<img width="360" alt="firefox disable tracking protection for this site drop-down" src="https://user-images.githubusercontent.com/30746/36328871-ccc9fdba-1331-11e8-83b5-43b213ed3b10.png">

The following is what happens in the various places you mentioned, without disabling tracking protection:

-    Navbar menu sign-in

If you mean the panel on the left, I don't see a sign-in option there.

-     Notifications

When I click on the notification icon, 

<img width="522" alt="dev to notifications login modal" src="https://user-images.githubusercontent.com/30746/36328875-cd89d428-1331-11e8-811b-41a61054ae85.png">

I see three warnings like this:

> Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.

And then the word 'hello'.

When I click the Twitter or Github buttons, nothing additional is logged.

-     Home page, top right widget

When I click the nine-squares icon, it drops down a menu.  

<img width="260" alt="dev to nine-squares drop-down" src="https://user-images.githubusercontent.com/30746/36328874-cd57530e-1331-11e8-82dc-817c60d07822.png">

When I click "Sign in via Twitter", it logs the following error, but it does work:

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://abs.twimg.com https://abs-0.twimg.com https://twitter.com https://mobile.twitter.com”). Source: onfocusin attribute on DIV element.

-     Home page, a little below the feed

If I click Twitter, it logs the same "Content Security Policy" error error as with the top right icon, but also works.

<img width="523" alt="dev to in-feed sign-in panel" src="https://user-images.githubusercontent.com/30746/36328873-cd2517c2-1331-11e8-850c-a4b8bd84a273.png">


-     Interacting with something (modal show up)

When I click in a comment field, the sign-in modal pops up, but nothing is logged, either when it pops up or when I click the Twitter button.

<img width="499" alt="dev to click in comment field sign-in modal" src="https://user-images.githubusercontent.com/30746/36328872-ccf72b6e-1331-11e8-8d47-9dec0a30cf1e.png">

One other thing to mention, is that when I refresh the home page, it logs the following warnings, in addition to dozens of google-analytics warnings:

> The resource at “https://connect.facebook.net/en_US/fbevents.js” was blocked because tracking protection is enabled.
> Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”.

**Comment by Zhao-Andy** [comment] 2018-02-16 21:07
Awesome, really appreciate all the feedback. I'll take a deeper look into it, thanks a lot!

**Comment by Zhao-Andy** [comment] 2018-03-09 20:03
Should be fixed now, let me know if otherwise. We just merged it in so probably wait a half hour before it gets deployed.

**Closed by Zhao-Andy** 2018-03-09 20:03 UTC
