### ISSUE TITLE
email is not visible in dark mode

### ISSUE THREAD

**Issue by Seniru** [thepracticaldev/dev.to#4907] opened 2019-11-25 06:54 UTC
**Describe the bug**
This is related with the dark mode. As I mentioned in the title, the email is not clearly visible in profiles when we have turned on dark mode. The reason email text color is too dark and cannot identify separately with the dark mode.

**To Reproduce**

- Turn on dark mode
- View a profile (*https://dev.to/seniru*)
- You will notice the email text is not visible

**Expected behavior**

The email text should be lighter in dark mode so users can see it easily

**Screenshots**

![image](https://user-images.githubusercontent.com/34127015/69518665-24727c00-0f7e-11ea-9a11-b92b84d4c12e.png)
![image](https://user-images.githubusercontent.com/34127015/69518669-29373000-0f7e-11ea-8802-4bfafdfeb926.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 78.0.3904.108 (Official Build) (64-bit)

**Smartphone (please complete the following information):** Not tested

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment] 2019-11-25 11:53
Hi @Seniru, thanks for the PR! I'm closing this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/4907

**Closed by rhymes** 2019-11-25 11:53 UTC
Labels: triage

**Comment by Seniru** [comment] 2019-11-25 16:26
I'm sorry if this issue exists already. *i tried my best to find duplicates*

I think you have mentioned #4907 accidentally as a duplicate of this issue 😅

**Comment by rhymes** [comment] 2019-11-25 16:38
Sorry @Seniru I meant https://github.com/thepracticaldev/dev.to/issues/4892
