### ISSUE TITLE
Not loading my pen project

### ISSUE THREAD

**Issue by CalvinTaylor40** [thepracticaldev/dev.to#4304] opened 2019-10-07 21:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS:
- Browser:
- Version:

**Smartphone (please complete the following information):**

- Device:
- OS:
- Browser:
- Version:

**Additional context**

**Comment by rhymes** [comment] 2019-10-08 10:58
Hi @CalvinTaylor40 can you add more details? It's unclear what the issue is about. Thanks!

**Comment by jessleenyc** [comment] 2019-10-14 13:44
Hey @CalvinTaylor40 I'm going to close this issue for now since we don't have enough information. Feel free to open a new one with more info!

**Closed by jessleenyc** 2019-10-14 13:44 UTC
Labels: triage

**Comment by CalvinTaylor40** [comment] 2019-10-14 13:50
Sorry the issues was sharing from codpen to here mulitpul times i wouldbtry to share what i put together and share it here and a error page came up
