### ISSUE TITLE
Overflow issues

### ISSUE THREAD

**Issue by uyouthe** [thepracticaldev/dev.to#3529] opened 2019-07-22 20:49 UTC
<img width="1240" alt="Screenshot 2019-07-22 at 23 39 47" src="https://user-images.githubusercontent.com/14220138/61663858-385d5700-acda-11e9-8e81-4063244bdb4b.png">

see https://dev.to/guruguy00

I think the reason is absolutely positioned `user-metadata-details`. Its container thus has no clue about how tall it needs to be to fit this.

I've examined `user-profile-header` and its behaviour. The variants are:
1. Wide screen. `user-metadata-details` is at the right as one column
2. Not so wide screen. `user-metadata-details` is at the bottom as two columns
3. Narrow screen. `user-metadata-details` is at the bottom in one column.

This could be done just with making both `user-metadata-details` and `user-profile-header` flex elements. `user-profile-header` should wrap it's two inner containers (email-location-education and work-work_status-joined) while `user-metadata-details` should wrap `user-profile-header-container` and the whole `user-profile-header`.

Grids may help too.

**Comment by rhymes** [comment] 2019-07-22 20:54
@uyouthe I've added the link to the profile so that people can quickly see and inspect the problem live

**Comment by maestromac** [comment] 2019-07-24 16:10
Thanks for the detailed issue report @uyouthe . This is a duplicate of https://github.com/thepracticaldev/dev.to/issues/3253. You are encouraged to continue the conversation there!

**Closed by maestromac** 2019-07-24 16:10 UTC
Labels: bug, status: approved
