### ISSUE TITLE
Page Views

### ISSUE THREAD

**Issue by KevBurnsJr** [thepracticaldev/dev.to#79] opened 2017-08-24 01:17 UTC
I'd like to see how many page views my posts have.

**Comment by jessleenyc** [comment] 2017-08-29 01:31
Hey @KevBurnsJr! Thanks for the request, this is something we're working on. Closing this issue because it's a duplicate of https://github.com/thepracticaldev/dev.to/issues/27.

**Closed by jessleenyc** 2017-08-29 01:31 UTC
Labels: enhancement
