### ISSUE TITLE
After Twitter auth it claims I am offline

### ISSUE THREAD

**Issue by rugk** [thepracticaldev/dev.to#2919] opened 2019-05-21 16:14 UTC
**Describe the bug**
The Twitter auth does not work.

**To Reproduce**

1. Sign in with GitHub.
2. Try to connect Twitter.

**Expected behavior**
Works.

**Screenshots**
![](https://user-images.githubusercontent.com/11966684/58112638-34d32400-7bf4-11e9-9ebf-f897cfae91d2.png)

**Desktop (please complete the following information):**

- OS: Fedora 30
- Browser Firefox 68

**Comment by Zhao-Andy** [comment] 2019-05-21 16:17
Hmm, hard to say what the cause is but it might be OS related. Could we see your browser console's logs?

You can also try resetting your service workers in Firefox via `about:serviceworkers` and unregistering dev.to's service worker.

**Comment by rugk** [comment] 2019-05-21 17:06
Don't know how to get these logs…

`about:debugging` shows me this:
![image](https://user-images.githubusercontent.com/11966684/58115941-71564e00-7bfb-11e9-9240-c7b98168334c.png)

`about:serviceworkers`
![image](https://user-images.githubusercontent.com/11966684/58115963-7c10e300-7bfb-11e9-94f7-8514dc8a9071.png)

**Comment by rugk** [comment] 2019-05-21 17:12
Unregistered the service worker and trying again did not work.

On the `https://dev.to/users/auth/twitter/callback/…` site itself, no (special) logs were displayed.

**Comment by hwolfe71** [comment] 2019-05-22 20:06
Could this be related to bug #2790?

**Comment by rugk** [comment] 2019-05-22 20:10
Mhh, could be, don't know.

**Comment by jessleenyc** [comment] 2019-06-14 23:24
@rugk #2790 has been fixed but we still have some other service worker issues as seen in #1810. However, want to try to logging in and see if it works for you?!

**Comment by rugk** [comment] 2019-06-15 22:06
I actually noticed another thing:
* This time, if I clicked "login with Twitter" and navigated back from the Twitter auth page -> It then also showed me the "Dev is offline" page for some reason.

**Comment by rugk** [comment] 2019-06-15 22:08
And the original issue also still continues…

**Comment by maestromac** [comment] 2019-06-17 16:11
@rugk can you please share your browser's log?

**Comment by rugk** [comment] 2019-06-17 20:00
It worked now . :thinking:

**Comment by maestromac** [comment] 2019-06-19 22:59
I'm assuming the service worker's cache got cleared because of we rolled out the new version. 

If the issue returns please let me know!

**Comment by rugk** [comment] 2019-06-20 11:21
Okay, no, I can still reproduce this. But only on one device/with one browser…

**Comment by rugk** [comment] 2019-06-20 11:21
Okay, a Ctrl+F5 on the "You are offline" page fixes it, but I have to do this each time… :thinking:

**Comment by maestromac** [comment] 2019-06-20 15:33
Which browser is this? Can I also have the browser's log?

**Comment by rugk** [comment] 2019-06-20 17:50
It's still the same from the OP. 
![image](https://user-images.githubusercontent.com/11966684/59869899-adb0d180-9394-11e9-88df-aeeed29e3e93.png)

**Comment by rugk** [comment] 2019-06-20 17:52
For some reason, I cannot inspect the service worker in Firefox though… :thinking: 

![image](https://user-images.githubusercontent.com/11966684/59870002-e51f7e00-9394-11e9-9489-e1806856f417.png)

**Comment by Zhao-Andy** [comment] 2019-06-20 17:54
Meant to ask this earlier but do you have any extensions? Like Privacy Badger or uBlock, for example?

**Comment by rugk** [comment] 2019-06-21 12:55
yep, many.

**Comment by jessleenyc** [comment] 2019-07-30 14:10
Ah okay - sounds like you're experiencing this bug: https://github.com/thepracticaldev/dev.to/issues/168

Going to close this issue as a duplicate.

**Closed by jessleenyc** 2019-07-30 14:10 UTC
Labels: bug
