### ISSUE TITLE
[Resolved via rollback] articles being duplicated on edit

### ISSUE THREAD

**Issue by liyasthomas** [thepracticaldev/dev.to#4502] opened 2019-10-19 23:49 UTC
**Describe the bug**

Editing an existing article and publishing it creates new copy of the article and publish that.

**To Reproduce**
1. Edit an existing article
2. Save changes and publish
3. See copy of the article is published and old one still exists

**Expected behavior**
Existing article should be updated rather than creating new article.

**Screenshots**

**Desktop (please complete the following information):**

- OS: 
- Browser: 
- Version: 

**Smartphone (please complete the following information):**

- Device: MotoG5S+
- OS: Android
- Browser: Chrome
- Version: latest

**Additional context**
I checked the article slug, it's also updated.

**Comment by liyasthomas** [comment] 2019-10-19 23:51
#4501

**Comment by hoangvvo** [comment] 2019-10-20 00:15
I can reproduce. Having the same problem.

If no edit is made on the body (like me trying to urgently add the Canonical URL before Google flag my original post :rofl:), the one below is shown.

![Screenshot_2019-10-19](https://user-images.githubusercontent.com/40987398/67152898-d1d1e000-f2ac-11e9-8651-71c44d43e512.png)

If edits are made on the body, the post is duplicated.

**Comment by hoangvvo** [comment] 2019-10-20 00:18
The console showed a `TypeError: r is undefined` at this location

![Screenshot from 2019-10-19 20-17-13](https://user-images.githubusercontent.com/40987398/67152923-7c4a0300-f2ad-11e9-9043-8abd1a91e015.png)

**Comment by hoangvvo** [comment] 2019-10-20 00:45
cc @benhalpern

**Comment by benhalpern** [comment] 2019-10-20 01:16
I'm seeing this now. Any initial ideas about what's going on?

**Comment by liyasthomas** [comment] 2019-10-20 01:44
What was the last modification on article edit feature? Check last 5 such PRs and will get a thread. I'm investing what caused this, but you guy could do it better.

**Comment by hoangvvo** [comment] 2019-10-20 01:51
@benhalpern 
The error was resolved. I guess you just just rolled back?

I do not know if this is intentional but the `POST` request body contains everything even the HTML of the error component and the help component.

Also, when I tried to save the edit, it made a `POST` request (I assumed it would be `PUT`?). Deleting a post also make a `POST` request.

**Comment by benhalpern** [comment] 2019-10-20 01:52
Yeah I rolled back. And I agree it seems resolved.

I believe it was this PR, which I merged earlier tonight.

https://github.com/thepracticaldev/dev.to/pull/4217

This makes sense. It affected the editor.

I _believed_ it was a safer merge than it was, or else I wouldn't have merged it on a Saturday. I was trying to catch up after taking yesterday off. Not a good idea, I should have been more careful.

**Comment by benhalpern** [comment] 2019-10-20 01:56
I'm going to leave this open, but modified the title to reflect the status.

The problematic code is still in the master build for now.

**Comment by hoangvvo** [comment] 2019-10-20 02:29
@benhalpern
I just looked at #4217 several minutes ago and saw some thing weird. Correct me if I'm wrong.

I see we submit the article via on `this.state`:
```
submitArticle(state, this.removeLocalStorage, this.handleArticleError);
```

However, looking at `state`, some of the props are removed. I'm not sure if those props are obsoleted or removed by accident.

![Screenshot from 2019-10-19 22-22-09](https://user-images.githubusercontent.com/40987398/67153874-37c76300-f2bf-11e9-90fe-a9a579f103a7.png)

**Comment by hoangvvo** [comment] 2019-10-20 02:41
If that is the case, mind if I make a PR? I would also like to remove unnecessary prop when it is passed into `submitArticle` (such as `helpHTML`). The payload is kinda big with them.

**Comment by rhymes** [comment] 2019-10-20 09:03
Hello everyone, I reviewed that PR multiple times at each step but I didn't notice that `editing` disappeared from the state. I think the OP removed those props because he couldn't find where they were used in the file itself.

I should have tested it more thoroughly, sorry :-( 

I've been trying to test all of these "fix lint errors" PRs manually because honestly I don't think we have sufficient automated testing in the frontend, be it the vanilla JS which has none or the preact layer that is under tested but apparently that slipped through the manual testing nonetheless.

@benhalpern I wonder if we should wait for a double "approve" for all these "linting" PRs so that we're sure there are at least 2 sets of eyes on them or, except from trivial changes, request tests with refactoring PRs (which makes sense, since you're touching untested code) the same way we do with the backend code

**Comment by johannesjo** [comment] 2019-10-20 12:04
I wonder is there any way to merge the duplicate article with the "old" post again?

**Comment by nickytonline** [comment] 2019-10-20 19:46
This could be a great time to introduce some e2e testing as @rhymes suggests. I opened this a while ago, but it went stale, #382. I also see a PR was opened in August (#3679) for Cypress as well.

As a first iteration if we're not completely setup to have a test environment in CI/CD, we could just run the tests locally before a deployment and a second phase could be to add it to the CI/CD pipeline. Thoughts?

**Comment by rhymes** [comment] 2019-10-21 08:45
@nickytonline I agree with the idea of adding e2e through Cypress, both manually and through the CI. I see you reviewed the PR, thank you!

**Closed** 2019-10-21 19:40 UTC
Labels: area: publishing experience, type: bug
