### ISSUE TITLE
Timestamps on notifications

### ISSUE THREAD

**Issue by mcataford** [thepracticaldev/dev.to#2010] opened 2019-03-08 23:52 UTC
**Is your feature request related to a problem? Please describe.**
I was looking at my Notification history earlier today and noticed that individual notification cards aren't timestamped, which can be a bit confusing if you are trying to look at a larger notification stream and need to know details about when replies were posted.

![Screenshot from 2019-03-08 18-48-55](https://user-images.githubusercontent.com/6210361/54062272-12c02d00-41d3-11e9-903d-6e59876729ed.png)

**Describe the solution you'd like**
The timestamp of each notification should be visible in the Notifications tab.

**Describe alternatives you've considered**
Opening up each notification, which gets troublesome really fast.

**Additional context**
I'd be happy to take this on, but I'm not sure if it's a feature that was left out intentionally because of some technical limitation. It would be awesome to have that extra temporal context around notifications.

**Comment by jessleenyc** [comment] 2019-03-12 19:38
@mcataford since this will involve some design, will you share your mockups with us before implementing? This is approved once we're on the same page about how it'll look.

**Comment by mcataford** [comment] 2019-03-12 21:31
Absolutely!

Will get to that today and post it here.

**Comment by mcataford** [comment] 2019-03-13 01:23
This could be a very basic way of doing it. I'm not aware of a public styleguide or set of visual guidelines re:accessibility and design, so I preserved the pre-existing top spacing between the comment box and the notification title, and used 14px for text to avoid stealing focus from the 18px title or surrounding text.

In this scenario, the post date would stand on its own line between the title string and the comment box.

![Screenshot from 2019-03-12 21-18-24](https://user-images.githubusercontent.com/6210361/54246723-78325780-450c-11e9-9994-d16fd8d447a8.png)

What do you think?

**Comment by jessleenyc** [comment] 2019-03-13 15:25
@mcataford this looks good to us for comments/posts. We do have other types of notifications: badges, milestones, new followers, new reactions, etc. We're cool with just adding timestamps to comments/posts to start but if you wanted to give the other types some thought that might make sense too.

Adding some screenshots as examples of the different styles.

![](https://cl.ly/d54b58fdcf97/download/Image%202019-03-13%20at%2011.23.48%20AM.png)
![](https://cl.ly/20ca9dd05093/download/Image%202019-03-13%20at%2011.24.05%20AM.png)
![](https://cl.ly/7b3c0458f61e/download/Image%202019-03-13%20at%2011.24.31%20AM.png)
![](https://cl.ly/5d15259546a3/download/Image%202019-03-13%20at%2011.25.05%20AM.png)

**Comment by mcataford** [comment] 2019-03-13 15:51
For the aggregates (i.e. `Jill and 101 others have reacted to this`), the timestamp might not make total sense (since there would be a timestamp per reaction, which muddies the meaning of the timestamp IMO), but for single reactions and for the badge-type notification, it definitely does. I'll give it some thought and try to generate all the notification types locally.

**Comment by Zhao-Andy** [comment] 2019-03-13 15:59
@mcataford let us know if you have questions generating the notifications. IMO the best way is to generate them in `rails console` and run the class methods from `notification.rb` without delay. For example:
```ruby
# follow notification
me = User.last
follow = User.first.follow(me)
Notification.send_new_follower_notification_without_delay(follow)

# reaction notification
rxn = Reaction.create(
  user_id: 1,
  category: "like",
  reactable: me.articles.last, # this assumes you have an article written
)
Notification.send_reaction_notification_without_delay(rxn, me)
```

**Comment by mcataford** [comment] 2019-04-18 02:23
(Bumping this to say that it's still on my radar, it's just been a busy little while. :sweat_smile:)

**Comment by ClaraMorgen** [comment] 2019-05-29 07:43
I created another issue #2997 , because I find it confusing to see the timestamp from the notifcation and not from the creation time of the post.  
I am not sure if this is entirely separate and what the expected behaviour exactly is. 

Also it doesn't update the timestamp - I have a notification saying "made a new post: 6 minutes ago" for the past two hourse.

**Comment by wolfhoundjesse** [comment] 2019-06-05 11:47
> Also it doesn't update the timestamp - I have a notification saying "made a new post: 6 minutes ago" for the past two hourse.

That might explain why I woke up to this minute-ago-notification about something that took place last night!

![image](https://user-images.githubusercontent.com/13468509/58954061-1cbbe280-8766-11e9-8785-0b17edc54dcc.png)

**Comment by jessleenyc** [comment] 2019-08-07 22:51
Going to close this since the original issue has been resolved.

**Closed by jessleenyc** 2019-08-07 22:51 UTC
Labels: help wanted, type: feature request
