### ISSUE TITLE
User Can't Import A Specific Article from Medium Via RSS Import Functionality

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#3070] opened 2019-06-06 23:09 UTC
**Describe the bug**
We received a report from a user earlier this week that their DEV account stopped fetching posts from their RSS import. (They'd set DEV to automatically import articles posted to their Medium.) THey've tried re-entering the URL and clicking "Fetch Feed Now", but are still not see new draft entries added to their dashboard. 

The feed URL is https://medium.com/feed/@kaustavdm and they're dev.to username is @kaustavdm.

The missing entry they noticed is ["APIOps: The art of mixing APIs"](https://medium.com/better-practices/apiops-the-art-of-mixing-apis-b0d85de88864).

*QUICK NOTE* They gave me permission to share personal details when posting this.

**Expected behavior**
The post should load into their dashboard successfully.

**Screenshots**
If need be, I can provide a transcript of the actual conversation, but I think this should cover all the key points.

**Comment by setevoy2** [comment] 2019-06-07 08:19
Can confirm.
My post also wasn't added to Drafts on Dev.to via RSS.
The post was published on the blog: https://rtfm.co.ua/en/jenkins-running-phpunit-from-codeception-by-a-pull-reguest-in-github-and-allure-reports/
It is present in the blog's RSS feed: https://rtfm.co.ua/en/feed
This feed is configured on the Dev.to and previously all was working.
On the Dev.to Settings page - _RSS Last Fetched: 7 June, 11:07:56_, while the post was added 6 June and still wasn't added to the Drafts.

**Comment by setevoy2** [comment] 2019-06-17 07:57
> opened this issue 10 days ago
And still no updates on this, team? :-(

**Comment by maestromac** [comment] 2019-06-18 20:03
Sorry for the delay @setevoy2 . 

It looks like your RSS feed [isn't valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frtfm.co.ua%2Fen%2Ffeed%2F). I'd recommend you follow W3C's feed validator's suggestion and then retry fetching your feed from dev.to

**Comment by maestromac** [comment] 2019-06-18 20:26
Our RSS reader could not fetch the missing entry, ["APIOps: The art of mixing APIs"](https://medium.com/better-practices/apiops-the-art-of-mixing-apis-b0d85de88864), is because the post happens to include the following.

> For example, a common practice is to use a {{base_url}} ...

That is considered a [Liquid Variable](https://shopify.github.io/liquid/tags/variable/) and is disabled by in our MarkdownParser. I'm working on a workaround.

**Comment by setevoy2** [comment] 2019-06-19 09:21
> It looks like your RSS feed [isn't valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frtfm.co.ua%2Fen%2Ffeed%2F).

Oh, I see...
Thanks a lot, @maestromac - fixed now.
Will dev.to now re-read this feed to add already published posts? Or I need to re-post them on my blog to make them appear in the RSS again?

**Comment by kaustavdm** [comment] 2019-06-20 12:09
@maestromac I just realized that the presence of double curly braces might result in markdown parsing issue. I came here to let you know that. And, you seem to have beat me to it. 🖤

**Comment by maestromac** [comment] 2019-06-20 19:28
Resolved with https://github.com/thepracticaldev/dev.to/pull/3229

**Closed by maestromac** 2019-06-20 19:28 UTC
Labels: bug

**Comment by setevoy2** [comment] 2019-08-15 19:55
Hi, team.
Faced again with the same issue, sorry :-(
Checked RSS - [it's valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frtfm.co.ua%2Fen%2Ffeed%2F).
Post to be imported to the Dev.to:
https://rtfm.co.ua/en/kubernetes-part-3-aws-eks-overview-and-manual-eks-cluster-set-up
It's present [in the feed](https://rtfm.co.ua/en/feed/).
It was published about 3-4 hours ago, but wasn't added as a Draft to the Dev.to.
Is it anything from my side again?

**Comment by jessleenyc** [comment] 2019-08-16 17:05
Hey @setevoy2 can you try re-saving your RSS feed and see if it pulls the draft in?

**Comment by setevoy2** [comment] 2019-08-16 21:17
Hi, @jessleenyc 
Re-saved post in my WordPress blog (this must trigger RSS update somehow, I guess?) - but still nothing on Dev.to.

**Comment by jessleenyc** [comment] 2019-08-19 23:07
Hey @setevoy2 sorry, I meant re-submit the form on your DEV settings: https://dev.to/settings/publishing-from-rss!

**Comment by setevoy2** [comment] 2019-08-20 06:02
Well... Still didn't help :-(
Interesting if I'll add a new post - will it be submitted to Dev.to or not... 
Just have time to post something new now.

**Comment by setevoy2** [comment] 2019-08-20 12:28
Hey, @jessleenyc !
Interesting, but the [latest post](https://rtfm.co.ua/en/docker-compose-shared-networks/) was submitted to the Dev.to without any issues.
So - it's something wrong with exactly the [previous one](https://rtfm.co.ua/en/kubernetes-part-3-aws-eks-overview-and-manual-eks-cluster-set-up/).
Just can't understand what exactly :-(
Anyway - the issue is not on your side, so thanks for your time.
But if you can give me a hint - this will be great.

**Comment by jessleenyc** [comment] 2019-08-22 13:09
@setevoy2  do you want to send a full markdown file to yo@dev.to so we can take a closer look at what's going on?

**Comment by jessleenyc** [comment] 2019-08-22 13:17
@setevoy2 we'll take a look at it. cc @Zhao-Andy

**Comment by Zhao-Andy** [comment] 2019-08-23 19:51
Hey @setevoy2, looks like there's an edge case coming from the markdown generated from that specific article. We'll look into fixing the edge case. I've put a working version of the markdown that you can use to create a draft of the same post into a gist here: https://gist.github.com/Zhao-Andy/c56949b75ec35d98760e10b949e9c807

In case you were wondering, the edge case that caused the issue is with the text `{{EC2PrivateDNSName}}`. The markdown generated from your RSS feed did not have this wrapped with backticks, and therefore caused an edge case with our markdown parser.

We use Liquid to create custom Liquid tags, and the `{{ }}` syntax is used by Liquid (and thus our parser). Since `{{EC2PrivateDNSName}}` was not wrapped in backticks, it was read as-is and caused a runtime error, and therefore failed to generate a draft post when being pulled by our RSS reader.

**Comment by setevoy2** [comment] 2019-08-24 04:06
Great, @Zhao-Andy! Many thanks!
I'll pay attention to the `{{ }}` next time. Usually, in code samples, they are enclosed with some ``, but at this time it was the terminal's output so it went to RSS "as is" :-)

**Comment by setevoy2** [comment] 2019-11-17 17:45
And here we are again, @jessleenyc @Zhao-Andy  ...
I'm sorry but have a similar problem again... 
Had the `{{ }}` in the newly added [Grafana: Loki – the LogQL’s Prometheus-like counters, aggregation functions, and dnsmasq’s requests graphs](https://rtfm.co.ua/en/grafana-loki-the-logqls-prometheus-like-counters-aggregation-functions-and-dnsmasqs-requests-graphs/) post, first thought it still not fixed, removed it, did "Fetch RSS again" in the Dev.to Settings, but didn't help...
Also, validated RSS via https://validator.w3.org/feed/ - it said all good...
Is there anything else I can try?
