### ISSUE TITLE
Show list of user who liked/bookmarked/unicorn 

### ISSUE THREAD

**Issue by sushant12** [thepracticaldev/dev.to#4030] opened 2019-09-16 08:55 UTC
**Is your feature request related to a problem? Please describe.**

I get notifications when someone likes my post but I dont get to see who liked them 

**Describe the solution you'd like**

 It would be nice to show list of user who liked my post when i  click on the number beside the icon (Just like in medium)

**Additional context**
If you like this idea, I can send a PR

**Comment by maestromac** [comment] 2019-09-16 13:25
Thank you for this issue @sushant12  . There already an issue on this. Please continue the conversation there.

Duplicate of https://github.com/thepracticaldev/dev.to/issues/160

**Closed by maestromac** 2019-09-16 13:25 UTC
Labels: triage
