### ISSUE TITLE
Ignore Tags for Feed Feature

### ISSUE THREAD

**Issue by smortime** [thepracticaldev/dev.to#5974] opened 2020-02-10 01:35 UTC
**Is your feature request related to a problem? Please describe.**

The feed requires a lot of scrolling to find posts relevant to personal interests. 

**Describe the solution you'd like**

The ability to ignore or reduce the amount of posts with specific tags from showing up on users feed can help customize the feed for individuals. For example a user can add "angular" or "javascript" to their ignored lists to stop seeing posts tagged with those on their feed. Another idea could be to add negative weight to tags so they are shown considerably less in a users feed. 

**Describe alternatives you've considered**

Could also take the opposite approach and only show things related to tags users follow. Feel like this could limit discovery of interesting topics though. 

**Additional context**

Believe this will help people interested in specific domains to tailor the feed to their interests while also giving them the ability to still discover tags / users / content without just looking at specific tags and ignoring feed completely when surfing dev.to :palm_tree:

**Comment by citizen428** [comment] 2020-02-10 06:14
Thanks for the report @smortime! I take it you experimented with the tag weights at https://dev.to/dashboard/following and found them not flexible enough, correct?

**Comment by rhymes** [comment] 2020-02-10 14:43
Hi @smortime, thanks a lot for this, it's definitely a heartfelt topic!

I'm going to close it as a duplicate of https://github.com/thepracticaldev/dev.to/issues/1856 - there's a longer discussion in there as well. Please feel free to add your thoughts there.

**Closed by rhymes** 2020-02-10 14:43 UTC
Labels: area: homepage, area: tags, type: feature request

**Comment by smortime** [comment] 2020-02-11 00:09
Thanks for the heads up @rhymes will take a look. Also going to play with more aggressive negative tag weights 👍
