### ISSUE TITLE
Posts are not listed in order of publication date in the tag feed

### ISSUE THREAD

**Issue by johnpapa** [thepracticaldev/dev.to#1838] opened 2019-02-20 19:54 UTC
**Describe the bug**
Posts are not listed in order of publication date

**To Reproduce**

1. Go to <https://dev.to/t/javascript>
2. Notice posts are not in the published date sequence

**Expected behavior**
Expected to see most recently published posts on top (or a sorting menu)

**Screenshots**
![image](https://user-images.githubusercontent.com/1202528/53120229-5fdba800-351f-11e9-85a3-45465398c621.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser chrome
- 72.0.3626.109

**Comment by maestromac** [comment] 2019-02-20 23:34
Thank you for this issue @johnpapa ! The Feed tab takes into account recent submissions, along with other factors such as reactions and comments.  The [Latest tab](https://dev.to/t/javascript/latest) provides submissions in a strict chronological order.

**Comment by benhalpern** [comment] 2019-02-21 04:25
Yep, as @maestromac mentioned, it's a "hotness" feed, not strictly chronological, similar to Reddit etc. I'll close this as it is intended behavior, but if you feel like this should be changed or needs clarification through design or anything else, feel free to open another issue.

**Closed by benhalpern** 2019-02-21 04:25 UTC
