### ISSUE TITLE
Git commit gives an error

### ISSUE THREAD

**Issue by keshavbiswa** [thepracticaldev/dev.to#2071] opened 2019-03-15 15:03 UTC
**Describe the bug**
Every commit I make I have to explicitly provide `--no-verify`  for husky to bypass otherwise I get an `Bundler::RubyVersionMismatch` Error. I have no idea why is this happening?

**To Reproduce**

1. Make some changes in any .rb file
2. git add .
3. git commit -m"Message"

**Expected behavior**
It should run rubocop without any error and accept my commit.

**Screenshots**
![Screenshot from 2019-03-15 20-49-47](https://user-images.githubusercontent.com/27268721/54442132-1c620b80-4764-11e9-82a1-1eb1d21d5c31.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser [chrome]

**Additional context**
Every other bundler related commands such as bin/startup works fine.

**Comment by lightalloy** [comment] 2019-03-15 16:57
I have also encountered this error. I think it's because the `lint-staged` runs rubocop using the system ruby version. It can be fixed by changing this line https://github.com/thepracticaldev/dev.to/blob/365a3513dc075a77165eb71fbba789b7e1809716/package.json#L29 to 
```bash
bundle exec rubocop --require rubocop-rspec --safe-auto-correct
```
Does anyone have thoughts on this fix?

**Comment by abraham** [comment] 2019-03-15 17:42
According to the bundler docs `bin/rubocop` should be identical to `bundle exec rubocop`.

https://bundler.io/v1.16/man/bundle-exec.1.html#BUNDLE-INSTALL-BINSTUBS

**Comment by lightalloy** [comment] 2019-03-15 18:37
@abraham somehow it's not, but only when run via `lint-staged`

**Comment by keshavbiswa** [comment] 2019-03-15 18:41
@lightalloy it doesn't work with `bundle exec rubocop` too

**Comment by maestromac** [comment] 2019-03-15 19:02
This sounds like an issue particular to your system. It may help but we would recommend rbenv over rvm.

For any issue unrelated to the codebase, please consider using our [discussion thread](https://dev.to/devteam/devto-open-source-helpdiscussion-thread-v0-1l45). Closing since this is unrelated to dev.to but you guys are welcome to keep the conversation going here.

**Closed by maestromac** 2019-03-15 19:02 UTC
Labels: bug

**Comment by lightalloy** [comment] 2019-03-15 19:12
I have the same issue using rbenv 🤷
I'll probably look more into this later.

**Comment by maestromac** [comment] 2019-03-15 19:15
@keshavbiswa what if you change your rvm's default to 2.6.1?

**Comment by lightalloy** [comment] 2019-03-19 10:52
@keshavbiswa in my case `npm-which` which is used by `lint-stage` gives the system ruby, whilst `node-which` gives the correct ruby.
```
# npm-which
light@lightosaurus:~/sites/dev.to$ yarn run npm-which ruby
$ /home/light/sites/dev.to/node_modules/.bin/npm-which ruby
/usr/bin/ruby # system ruby

# node-which
light@lightosaurus:~/sites/dev.to$ yarn run which ruby
$ /home/light/sites/dev.to/node_modules/.bin/which ruby
/home/light/.rbenv/shims/ruby # rbenv ruby (correct)

# system which
light@lightosaurus:~/sites/dev.to$ which ruby
/home/light/.rbenv/shims/ruby # rbenv ruby (correct)
```
I haven't dug any further.

**Comment by rhymes** [comment] 2019-03-19 11:43
Sometimes I wonder how our computers work at all, because we work on a never ending tower of code written by thousands if not millions of developers and such pieces of code somehow always work together like a LEGO (or at least most of the time :D) 

It's truly fascinating how magical it must look from the outside.

**Comment by abraham** [comment] 2019-03-19 15:44
The problem is computers do what we tell them to do, not what we want them to do.
