### ISSUE TITLE
UI Fixes in the website

### ISSUE THREAD

**Issue by harishkotra** [thepracticaldev/dev.to#669] opened 2018-09-16 05:53 UTC
## Task

Task 1: Remove footer from pages where there are auto loading posts on scroll
Task 2: Add target="_blank" to links for third party pages like Twitter, Github in the contact page.

### User Story / Description

Task 1: I tried reaching the footer to check the links but it doesn't make sense to have a footer when the user cannot even reach on pages where there are autoloading posts. The same links are anyways available in the sidebar on such pages.
Task 2: Clicking on Twitter/Github link takes to that page on the same tab and from there I lose track of dev.to and scroll through the timeline or check out repos on github. Tried going back but realized it opened in the same tab. 

### Current Behavior

Task 1: Footer is visible for a blink of a second
Task 2: Links open in same tab

### Expected Behavior

Task 1: Remove footer and make left sidebar scroll along with the page
Task 2: Links should open in a new tab

**Comment by Nirajn2311** [comment] 2018-09-19 13:40
Can I start working on this?

**Comment by harishkotra** [comment] 2018-12-19 12:16
This is not resolved or addressed yet. Issue persists on the live site.

**Comment by Nirajn2311** [comment] 2018-12-19 14:31
@harishkotra Cna I start working in this?

**Comment by maestromac** [comment] 2018-12-20 23:20
Hello @harishkotra, sorry we let this one slipped through. 

Regarding task 1 : This should've been spotted earlier but this is a duplicate of https://github.com/thepracticaldev/dev.to/issues/266
Regarding task 2 :  Seems like this is no longer an issue.


Also, in the future, please create a separate issue for each topic.

**Closed by maestromac** 2018-12-20 23:20 UTC
