### ISSUE TITLE
Trying to save some chars (like `=>`) in profile summary parse them to HTML entities

### ISSUE THREAD

**Issue by leandrw** [thepracticaldev/dev.to#164] opened 2018-02-23 21:24 UTC
# _BUG_
### Current Behavior
Trying to save some chars (like `=>`) in [Profile/Summary](https://dev.to/settings/profile) parse them to HTML entities.

### Expected Behavior
Keep exact description that you want

### Additional Info (steps to replicate, device/browser, helpful links)
Input some chars like `=>` in your *profile summary* then **submit**.

### Screenshots
What I typed
![selection_008](https://user-images.githubusercontent.com/1456009/36617405-1265b884-18c6-11e8-8fda-6a54ac3f8494.png)
After profile submitted
![selection_009](https://user-images.githubusercontent.com/1456009/36617410-18746e14-18c6-11e8-974a-c39427582b71.png)

**Comment by Zhao-Andy** [comment] 2018-02-27 17:05
Hey @leandrw, thanks for the heads up. We'll take a look into this bug and get back to you when it's fixed.

**Comment by rhymes** [comment] 2018-08-17 14:50
This can be probably closed @Zhao-Andy 

![bio](https://user-images.githubusercontent.com/146201/44272579-9289a880-a23d-11e8-8989-c41d2cb336ec.gif)

**Comment by Zhao-Andy** [comment] 2018-08-17 14:53
Ah, think you're right :) @maestromac wanna confirm/close this since you fixed this?

**Comment by maestromac** [comment] 2018-08-17 14:55
Yup, confirmed this is fixed!

**Closed by maestromac** 2018-08-17 14:55 UTC
Labels: bug
