### ISSUE TITLE
Unable to Remove Cover Image from post

### ISSUE THREAD

**Issue by nandhithakamal** [thepracticaldev/dev.to#9267] opened 2020-07-11 15:20 UTC
If a cover image is added to a post and later removed, this state is not preserved.
The cover image is removed in the preview but it pops back in in the actual post
Trying to edit the post to remove the cover image, has the cover image still present.

**Comment by rhymes** [comment] 2020-07-11 15:37
Hi @nandhithakamal, I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/6914 - let me know if I'm wrong! :)

**Closed by rhymes** 2020-07-11 15:37 UTC
Labels: triage

**Comment by nandhithakamal** [comment] 2020-07-11 19:24
Thanks, it is the same.
