### ISSUE TITLE
Infinite scrolling prevents reaching the footer

### ISSUE THREAD

**Issue by WellRedPandit** [thepracticaldev/dev.to#4096] opened 2019-09-23 15:52 UTC
**Describe the bug**

I scrolled to reach the footer to follow the links there to e.g. the code of conduct. The footer was not reachable. Or rather it appeared quickly to be immediately taken over by new contents.

I was able to reach the footer after I switched the browser to offline mode.

**To Reproduce**

1. Go to the homepage
2. Keep scrolling
3. See the footer run away from you

**Expected behavior**

Be able to stabilize the footer to follow the links in it.

**Desktop (please complete the following information):**

- OS: OS X 10.14.6
- Browser: Any
- Version: Any

**Comment by jessleenyc** [comment] 2019-09-23 16:20
Hey @WellRedPandit, any of the links you'd see on the homepage footer is also available in the lefthand sidebar. Closing this issue since it's a duplicate of #266

**Closed by jessleenyc** 2019-09-23 16:20 UTC
Labels: triage
