### ISSUE TITLE
I always get editor v2 but set v1 in the settings

### ISSUE THREAD

**Issue by kay-is** [thepracticaldev/dev.to#2824] opened 2019-05-14 11:48 UTC
**Describe the bug**
When I edit an article or create a new one, it gets opened in the v2 editor, but I want all to be opened in the v1 editor as I said in my settings.

**Expected behavior**
I would prefer all articles to be editable with v1

**Desktop (please complete the following information):**

- OS: Windows 7
- Browser: Firefox
- Version: 67.0b19 (64-Bit)

This v2 editor will be the death of me. It already deleted my content once and just now it said "Publishing" when I hit save, but I didn't want to publish. It didn't publish, but it said it would and I almost got a heart attack.

**Comment by Zhao-Andy** [comment] 2019-05-14 15:53
Hey @kay-is, we recently updated the v1 editor with features from the v2 editor, such as auto saving. The new v1 editor looks similar to the v2 editor, but the inputs -- using front matter and markdown -- are still the same.

Also great point about the `Publishing...` part. We'll definitely update that language properly.

Check out Ben’s post for more details: https://dev.to/devteam/changelog-upgraded-editor-45mk

If you still have your content deleted though, let us know and we can take a look into that as well. Otherwise the auto saving should be working as intended.

**Comment by kay-is** [comment] 2019-05-14 17:10
Ah, sad to hear that. The old editor had superior UX. Feels like a step back to me.

No, no deletions anymore. Just everything become more clunky.

Is there an API I can use to create articles?

**Comment by kay-is** [comment] 2019-05-15 18:09
Could you at least put the images and organization stuff down in the toolbar to the save/preview buttons?

Every time I want to add an image, I have to scroll down to the end, click the image button and then scroll up to upload the image, because the form is somewhere at the top.

**Comment by Zhao-Andy** [comment] 2019-05-15 18:19
Thanks for the feedback! I think moving the image upload makes sense; I'll defer to the rest of the team in terms of design choices.

The API should be coming soon. :) Here's a related PR regarding that: https://github.com/thepracticaldev/dev.to/pull/2844

**Comment by Zhao-Andy** [comment] 2019-05-15 18:30
Also we've updated the text from "Publishing" to "Saving" when saving a draft. PR: https://github.com/thepracticaldev/dev.to/pull/2831

**Comment by kay-is** [comment] 2019-05-15 18:32
Yes, saw that. Thanks. 😊

**Comment by kay-is** [comment] 2019-05-21 13:19
Can we get rid of the scroll-in-scroll?

Somehow the text area has a scroll indicator that only allows to scroll a few centimeters and the whole page has one used to scroll the whole document.

![Imgur](https://i.imgur.com/P27yXvh.png)

**Comment by jessleenyc** [comment] 2019-05-22 18:36
Hey @kay-is! Just created a new issue to address the scrollbar: https://github.com/thepracticaldev/dev.to/issues/2939

I'm going to close this one since we updated the text from publishing -> saving and explained that the v1 editor got some updates recently.

**Closed by jessleenyc** 2019-05-22 18:36 UTC
Labels: discussion
