### ISSUE TITLE
Submitting a user report redirects to 404 page

### ISSUE THREAD

**Issue by Eros** [thepracticaldev/dev.to#3005] opened 2019-05-29 23:35 UTC
**Describe the bug**

Upon reporting abuse of a users comment it asks for the reason, extra info, confirmation etc this is fine. But upon submitting it the submission will redirect to a error page

**To Reproduce**

1. Click report abuse on the message
2. Fill out the form
3. Confirm you're not a *beep boop bop* I mean robot
4. Be redirected to error page

**Expected behavior**
Not sure on what it's meant to show but probably not this

**Screenshots**
https://i.imgur.com/8fKrYYk.gifv

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 74.0.3729.169

**Comment by aspittel** [comment] 2019-05-30 22:49
Hey @Eros, thanks for flagging this! We'll take a look and get back to you!

**Comment by maestromac** [comment] 2019-05-31 12:06
My guess is that the spam comment was already deleted but the cache wasn't refreshed yet. So an attempt was made to report a comment that no longer existed. We either need to improve the cache invalidation or improve error handling on the report side.

**Comment by nicovillanueva** [comment] 2019-05-31 20:32
Heyo! Not sure if this adds anything, but when reporting listings (https://dev.to/listings) this same behavior occurs!

**Comment by fluffy-critter** [comment] 2019-06-02 15:47
I’m having the same thing happen, and it’s on comments which have definitely not been deleted yet. Now I’m not sure if my reports on a couple of comments have gone through.

**Comment by fluffy-critter** [comment] 2019-06-02 16:44
Reproduction steps (now that I'm on desktop):

1. Go to a comment reporting form, such as https://dev.to/report-abuse?url=http://dev.to/jorgecc/comment/bcmf?i=i
2. Fill out the reason (in this case, 'other')
3. Satisfy the Google Recaptcha overlords
4. Get redirected to https://dev.to/feedback_messages which is a 404

**Comment by maestromac** [comment] 2019-06-03 23:25
Resolved with https://github.com/thepracticaldev/dev.to/pull/3038

**Closed by maestromac** 2019-06-03 23:25 UTC
Labels: bug
