### ISSUE TITLE
Bug: Recommended article links below an article do not work

### ISSUE THREAD

**Issue by docoprusta** [thepracticaldev/dev.to#163] opened 2018-02-16 08:03 UTC
Great page for great community! I'm a big fan of the site :)

# _BUG_
### Current Behavior
Below an article there are 4 recommended article links. 2 link on the left side do not work (the href attribute is empty). If I click on it, it is going to the top of current page.

### Expected Behavior
Go to the clicked article.

### Additional Info (steps to replicate, device/browser, helpful links)
I perceived it in this [Article](https://dev.to/_patrickgod/making-story-driven-indie-games-with-no-budget-3dmj)

**Update**
I tried it with opera and chrome. If I am not logged in I receive different articles and they are work. If I am logged I receive these and go to the top of the page. Maybe the articles not exist anymore?

### Screenshots
![bug1](https://user-images.githubusercontent.com/24683720/36298348-f8208ce8-12f7-11e8-8e41-6a2936472b72.PNG)
This 2 do not work. The other 2 work correctly.

**Comment by Zhao-Andy** [comment] 2018-02-16 15:38
Hey @docoprusta, not sure what happened there, and I can't reproduce it. :( The articles there do exist, but the `href` should be filled in.

Those articles are cached, so you probably won't find the exact same articles again, but if you happen to still have the page up let us know if you find anything new.

**Comment by docoprusta** [comment] 2018-02-17 08:41
I made the bug report from my workplace computer. I tried it at home from my computer and I receive different articles and the links are working so I also can't reporduce the bug :(

**Comment by Zhao-Andy** [comment] 2018-02-19 16:20
Gotcha :( Well if you can, feel free to reopen this ticket. Going to close it since I couldn't find anything wrong code-wise on my first look.

**Closed by Zhao-Andy** 2018-02-19 16:20 UTC
