### ISSUE TITLE
Reading Scroll Progress Bar for Your articles in dev.to

### ISSUE THREAD

**Issue by yashwanth2804** [thepracticaldev/dev.to#5928] opened 2020-02-06 10:23 UTC
Better If we got this implemented in dev.to site articles too.
taken from [dev.to article](https://dev.to/xtrp/create-a-reading-scroll-progress-bar-for-your-blog-in-javascript-and-css-1jmc?signin=true)

**Comment by rhymes** [comment] 2020-02-06 11:19
Hi @yashwanth2804, thanks for opening this feature request! As this is a duplicate of https://github.com/thepracticaldev/dev.to/issues/1626 I'm going to close it and suggest you add a link to that article as a comment there :-)

**Closed by rhymes** 2020-02-06 11:19 UTC
Labels: triage
