### ISSUE TITLE
RSS Feed for Customized Profile

### ISSUE THREAD

**Issue by shanalikhan** [thepracticaldev/dev.to#597] opened 2018-09-05 09:20 UTC
I use Feedly for reading articles.
I have recently added Dev.to RSS but I'm getting a lot of articles.

What I want as a user of dev too. I have subscribed the tags and only want Feed that is available for those tags.
For example, I am following Feeds for 3 tags. Dev To should generate custom RSS Url for my profile something like:
dev.to/shankhan/feed/RSS

Should contains the articles for my tags.
In this way, I can only read articles I want though RSS applications.

**Comment by maestromac** [comment] 2018-09-05 16:27
Thanks for this issue @shanalikhan. This is a duplicate of #201. Closing as there's already a conversation going there.

**Closed by maestromac** 2018-09-05 16:27 UTC
