### ISSUE TITLE
400 response from Cloudinary with inline uploaded gifs

### ISSUE THREAD

**Issue by RoryO** [thepracticaldev/dev.to#7991] opened 2020-05-20 22:12 UTC
Cloudinary returning http status 400 for inline uploaded gif images. Original S3 link works fine. Cannot use S3 URL directly as the application rewrites the URL for inline viewing using Cloudinary instead.

**To Reproduce**

AWS URL from uploaded image, no issue

https://dev-to-uploads.s3.amazonaws.com/i/7afo799od7nrmgegw90v.gif

https://dev-to-uploads.s3.amazonaws.com/i/jam8uak08klab6mwbvum.gif

Cloudinary URL generated from application for inline display, returns http 400

https://res.cloudinary.com/practicaldev/image/fetch/s--eq7tttFD--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/7afo799od7nrmgegw90v.gif

https://res.cloudinary.com/practicaldev/image/fetch/s--_Al7yu2p--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/jam8uak08klab6mwbvum.gif

**Comment by rhymes** [comment] 2020-05-21 09:30
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by atsmith813** [comment] 2020-05-21 12:44
This is a duplicate, we've got a couple of issues open about this
https://github.com/thepracticaldev/dev.to/issues/7889.

I believe the issue is caused by larger GIFs and an issue with Cloudinary.

**Comment by mstruve** [comment] 2020-05-21 14:53
Closing since this is a duplicate

**Closed by mstruve** 2020-05-21 14:53 UTC
Labels: area: image uploader, area: publishing experience, type: bug
