### ISSUE TITLE
Combining tags together in a search query.

### ISSUE THREAD

**Issue by AntonRich** [thepracticaldev/dev.to#2238] opened 2019-03-29 13:53 UTC
It would be great if users could write a search query of the following format: #tag1 #tag2 and receive the results that actually have such tags.

https://dev.to/antonrich/how-can-i-combine-tags-when-searching-on-dev-to-5b19

**Comment by jessleenyc** [comment] 2019-03-29 14:56
Cool, thanks for creating the issue.

**Comment by srebalaji** [comment] 2019-03-31 15:08
Someone working on this feature? or Can I take it?

**Comment by maestromac** [comment] 2019-04-04 16:50
It's up for grab @srebalaji !

**Comment by omenking** [comment] 2019-04-07 03:35
Just going to document this for others and exploring the codebase myself.
So first I determined the request which is responsible for search.

<img width="551" alt="Screen Shot 2019-04-06 at 11 04 58 PM" src="https://user-images.githubusercontent.com/7776/55678018-8cc1ff80-58c0-11e9-9afa-30a9979565d9.png">

So now I'll go check out the routes to determine which action controller is being called:

```ruby
  get "/search" => "stories#search"
```
Lets take a look at that controller action:

```ruby
  def search
    @query = "...searching"
    @article_index = true
    set_surrogate_key_header "articles-page-with-query"
    render template: "articles/search"
  end
```

Surprisingly empty controller, maybe search logic is in views or `set_surrogate_key_header` is hiding the logic, nothing in before_actions and nothing in ApplicationController. A quick search for `def set_surrogate_key_header` pulls up nothing. Give google a search on `set_surrogate_key_header` and I  see `Fastly`, okay must be related to Fastly gem.

Going to check out the view, uncertain why its `render template: 'articles/search` instead of just `render 'articles/search'` maybe someone is using old syntax. Will proceed to check out views directory.

Looking around seeing lots of partials, going to inspect the one that I think may be best hint to find search functionality so settle on this one:

```ruby
<%= render "articles/algolia_search" %>
```

Oh wow, lots of inline javascript. This is probably the search functionality. Noticed the word `angolia` more than once, going to google search to see if I get the context.

<img width="522" alt="Screen Shot 2019-04-06 at 11 16 08 PM" src="https://user-images.githubusercontent.com/7776/55678088-00184100-58c2-11e9-9857-dc521cf9679d.png">

Oh, so maybe they are using a managed service called Angolia as their search engine, wonder what flavour of the search engine it is. Checking the js to get a feel of the API functionality.

Here I see client initialized to managed service and `search` function checking that search function.
```js
    var client = algoliasearch('<%= ApplicationConfig["ALGOLIASEARCH_APPLICATION_ID"] %>', '<%= ALGOLIASEARCH_PUBLIC_SEARCH_ONLY_KEY %>');
    var index = client.initIndex('searchables_<%= Rails.env %>');
    if (document.getElementById("query-wrapper")) {
      search(query, index, filters);
      initializeFilters(query, index, filters);
    }
``` 

Here is the search function, guessing this is where we can determine what we have to work with:

```
  function search(query, index, filters) {
    var searchObj = {
      hitsPerPage: 60,
      page: "0",
      queryType: "prefixNone",
      attributesToRetrieve: [
        'id',
        'title',
        'path',
        'class_name',
        'comments_count',
        'tag_list',
        'readable_publish_date',
        'positive_reactions_count',
        'flare_tag',
        'user'
      ],
      attributesToHighlight: [],
      exactOnSingleWordQuery: "none",
      attributesToSnippet: ['body_text:19', 'comments_blob:8'],
    }
    if (filters === "MY_POSTS" && userData()) {
      searchObj["tagFilters"] = [['user_' + userData()['id']]]
    } else {
      searchObj["filters"] = filters
    }
    index.search(query, searchObj)
      .then(function searchDone(content) {
        var resultDivs = []
        content.hits.forEach(function (story, i) {
          resultDivs.push(buildArticleHTML(story));
        })
        document.getElementById("substories").innerHTML = resultDivs.join("");
        initializeReadingListIcons();
        initializeAllFollowButts();
        document.getElementById("substories").classList.add("search-results-loaded");
        if (content.hits.length == 0) {
          document.getElementById("substories").innerHTML = '<div class="query-results-nothing">No results match that query</div>'
        }
      });
  }
```

Hmm, interesting, so would the tags actually be tokenized and weighted in the full-text search engine. Since I don't exactly know what's stored in Angolia search engine.  Going to check Angolia API documentation. Quick google search and here's a link:

[Angolia Filtering](https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/)

I see tags, wonder if these tags might match up to DEV.to article tags.

<img width="379" alt="Screen Shot 2019-04-06 at 11 28 18 PM" src="https://user-images.githubusercontent.com/7776/55678214-bf212c00-58c3-11e9-9b7b-061129c47ddb.png">

So far this sounds like if I wanted to filter by tags I'd use tags.

<img width="684" alt="Screen Shot 2019-04-06 at 11 29 23 PM" src="https://user-images.githubusercontent.com/7776/55678221-e1b34500-58c3-11e9-93ad-cdd541615fd4.png">

Here is the example they give. Though wonder how I could weight these higher than full text search results. Maybe just being explict with `_tags:` would be good enough
```
index.search('harry', {
  filters: 'politics' // Same as '_tags:politics'
});
```

If I am right we would still need to ensure in the UI that it highlights the tags so we indicate to the user 
that we are indeed searching in tags.

I should attempt to get the code running so I can test out angolia search functionality. Uncertain what kind of obstacles I'll have setting up a dev enviroment. Will check the repo root for a docker and instructions to run.

I am not claiming this ticket, so don't feel that my efforts here to discourage anyone to complete.

**Comment by omenking** [comment] 2019-04-07 13:20
I think my dev environment is working now. Took about 1 hour to pull everything on docker. When I get 30mins today I'll see what I can do to bring more domain knowledge on how to solve this ticket

**Comment by omenking** [comment] 2019-04-07 21:17
A bit more time before dinner so doing a bit more. I gave up on docker and just installed it on my system and the app is running now. 

Uncertain how to log in so I could make a post. Just getting around that by creating my on rake task to create a post:

```ruby
namespace :app do
  task article: :environment do
    user = User.first

    tags = ['security','go']

    markdown = <<~MARKDOWN
      ---
      title:  Best security practices when using go.
      published: true
      cover_image: #{Faker::Company.logo}
      tags: #{tags.join(', ')}
      ---

      If you are using the go langauge and you need to make
      things secure. These are the best security practices you can apply.
      #{Faker::Hipster.paragraph(2)}
      #{Faker::Markdown.random}
      #{Faker::Hipster.paragraph(2)}
    MARKDOWN

    Article.create!(
      body_markdown: markdown,
      featured: true,
      show_comments: true,
      user_id: user.id
    )
  end
end
```

I noticed the output suggested delayed job. I bet that means the search engine index was not updated. Going to inspect the last delayed job and invoke it manually via console:

```ruby
Delayed::Job.all.last.name # Article.index!
Delayed::Job.all.last.invoke_job
```

Uncertain if it worked trying to look at my Algolia GUI to see if I can find it in there.

**Comment by omenking** [comment] 2019-04-07 22:36
Neither option produced the desired result as it just worked as usual and I confirmed that I was correctly setting both configurations. I wonder if the tag values are actually stored in Alogia and/or if this is also a weighting issue.

**Comment by omenking** [comment] 2019-04-07 23:06
Wasn't too tricky. I have it working as how I think its expected now.
Going to fork and make a pull request

<img width="543" alt="Screen Shot 2019-04-07 at 7 06 03 PM" src="https://user-images.githubusercontent.com/7776/55691077-39a38780-5968-11e9-85b5-3c51c86fc88e.png">

**Comment by maestromac** [comment] 2019-10-08 22:35
Resolved with https://github.com/thepracticaldev/dev.to/pull/2322

**Closed by maestromac** 2019-10-08 22:35 UTC
Labels: area: search, help wanted, type: feature request
