### ISSUE TITLE
Add manual refresh option to fetch from RSS

### ISSUE THREAD

**Issue by pkfrank** [thepracticaldev/dev.to#1833] opened 2019-02-19 21:58 UTC
**Is your feature request related to a problem? Please describe.**
As an author with an RSS feed, I want DEV to import new posts from my RSS feed as they become available.  Currently, the [`/settings/publishing-from-rss`](https://dev.to/settings/publishing-from-rss) page has this copy:

> Your feed will be fetched every time you submit this form and updates will be automatically fetched periodically thereafter. Contact yo@dev.to if you encounter issues.

I don't think it's sufficiently clear and obvious to authors that hitting the `Submit` button will re-fetch posts.  I also think people are sometimes confused about _how long it should take_ for a new post available via RSS to appear as a draft in the dashboard.

**Describe the solution you'd like**
I think we should add a button to trigger a manual fetch from RSS 🔄.  Even if it would technically be the same action as hitting `Submit`, I feel like it would be more clear for authors.

Ideally, we can also have a status indicator that displays progress or a message that indicates when it was last fetched. 

> 🔄Re-Fetch Articles
> _last updated on Feb 19, 4:57pm_

**Comment by jessleenyc** [comment] 2019-02-26 13:19
We could also change the button to update as a quick enhancement.

**Comment by maestromac** [comment] 2019-02-27 16:05
Duplicate of https://github.com/thepracticaldev/dev.to/issues/539

**Closed by maestromac** 2019-02-27 16:05 UTC
Labels: approved, feature request, good first issue
