### ISSUE TITLE
Use fixed positioning for image button in article

### ISSUE THREAD

**Issue by omenking** [thepracticaldev/dev.to#2994] opened 2019-05-29 01:41 UTC
**Is your feature request related to a problem? Please describe.**
Lets say you've written a long article and now you need to insert about 14 images.

<img width="368" alt="Screen Shot 2019-05-28 at 9 37 39 PM" src="https://user-images.githubusercontent.com/7776/58523084-18edf600-8191-11e9-8872-dc133f855bbd.png">

The images button is all the way down at the bottom, you have to scroll all the way down, and then scroll all the way back up and the scroll back to your position. 

**Describe the solution you'd like**
Use fixed positioning for the image button.

**Describe alternatives you've considered**

**Additional context**

**Comment by aspittel** [comment] 2019-05-30 22:45
Hey @omenking, we've discussed this a bit in the past but haven't found a perfect solution design-wise. Thanks for flagging it, probably worth talking about again!

**Comment by omenking** [comment] 2019-05-31 01:31
Just put the image button in the fixed footer.

<img width="920" alt="Screen Shot 2019-05-30 at 9 30 13 PM" src="https://user-images.githubusercontent.com/7776/58675393-24bcf200-8322-11e9-94a7-4c81e0cdf52f.png">

**Comment by jessleenyc** [comment] 2019-06-04 19:50
Yeah, I agree that it makes more sense to be stickies at the bottom. Some additional things to consider: 
- how this would look on mobile
- how to would work with existing v2 editor buttons

**Comment by omenking** [comment] 2019-06-04 20:37
This is how it currently looks in mobile.
Is this editor not V2?

![Screen Shot 2019-06-04 at 4 22 41 PM](https://user-images.githubusercontent.com/7776/58911054-04f04a00-86e5-11e9-9eda-cfa988f11750.png)

This is my suggestion

![suggest](https://user-images.githubusercontent.com/7776/58911983-120e3880-86e7-11e9-88c0-619798700340.jpg)

**Comment by omenking** [comment] 2019-06-04 20:41
So this is V2 and it has different positions and is subject to the same problems.

@benhalpern is V2 not ready?

![Screen Shot 2019-06-04 at 4 39 57 PM](https://user-images.githubusercontent.com/7776/58912156-729d7580-86e7-11e9-9f26-f3eb5cba4744.png)

![Screen Shot 2019-06-04 at 4 39 51 PM](https://user-images.githubusercontent.com/7776/58912160-75986600-86e7-11e9-8f4a-9ca5744f93a1.png)

**Comment by Zhao-Andy** [comment] 2019-06-04 20:48
In the V2 editor the image upload button is to the right of tags input, next to the triple dots menu button.

I'm seeing the image upload button on mobile Android Firefox/DEV app:
![Screenshot_20190604-164303](https://user-images.githubusercontent.com/17884966/58912665-9d3bfe00-86e8-11e9-9518-97ed26ebaece.png)

I can't reproduce your mobile results with text overflow either. What browser/device is the mobile screenshot from?

**Comment by jessleenyc** [comment] 2019-06-04 21:23
To clarify, what I mean is we'll want to bring the additional button on V2 (the one next to the image button) into the fixed footer as well, if we move the v1 image button. This might make it pretty tight in that area.

**Comment by rhymes** [comment] 2020-06-26 11:26
Closing this as it's not applicable anymore in the new editor.

**Closed by rhymes** 2020-06-26 11:26 UTC
Labels: area: image uploading, area: publishing experience, future, hacktoberfest, ready for dev, tech: html/css, type: feature request
