### ISSUE TITLE
Reading List Posts Ordering Seems Off

### ISSUE THREAD

**Issue by michael-tharrington** [thepracticaldev/dev.to#7965] opened 2020-05-19 19:58 UTC
**Describe the bug**

When looking at my reading list, posts from 2018 have bumped their way up my list.

I'm assuming that the ordering scheme puts the most recently saved post at the top of my reading list... or potentially, the list is ordered by date published.

While I can't clearly tell the ordering scheme, there appears to be something off as a handful of articles published in 2018 are very high up my reading list.

**To Reproduce**

_NOTE: This may not be reproducible if you don't have lots of articles already in your Reading List_

1. Go to https://dev.to/readinglist
2. Look for signs that your posts may not be ordered correctly

**Expected behavior**

I'd expect to see posts listed in the order that I bookmarked them. But also, I think it would be acceptable for the posts to be listed in the order in which they were published.

In either condition, I think the order would be easily discernible.

**Screenshots**

Here's a screenshot of my reading list which shows the handful of 2018 posts (not recently bookmarked) at the top:

![Image 2020-05-19 at 3 44 59 PM](https://user-images.githubusercontent.com/16007075/82371705-a4871500-99e8-11ea-8561-ceabbc875139.png)

**Additional context**

A DEV user wrote a #meta post about this topic - https://dev.to/bertilmuth/order-of-items-in-reading-list-2j59, which made me wonder about my own reading list. Another commenter is experiencing the same issue with 2018 posts bumped up to the top of their reading list.

**Comment by rhymes** [comment] 2020-05-20 08:38
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To our amazing contributors: issues labeled `type: bug` are always up for grabs, but for feature requests, please wait until we add a `ready for dev` before starting to work on it.

To claim an issue to work on, please leave a comment. If you've claimed the issue and need help, please ping @thepracticaldev/oss and we will follow up within 3 business days.

For full info on how to contribute, please check out our [contributors guide](https://github.com/thepracticaldev/dev.to/blob/master/CONTRIBUTING.md).

**Comment by jacobherrington** [comment] 2020-05-26 16:16
I can confirm that this appears to be affecting my reading list as well.

However, I frequently add articles to my reading list and it's possible I added some 2018 articles to my reading list recently without noticing!

**Comment by ItsASine** [comment] 2020-06-15 17:12
As the "another commenter" I'd like to point out my case specifically is 
1. Oct 2018 saved articles
2. September 2018 saved articles
3. Everything else    
with each section being reverse chronological (newest first) based on save date

Anything I would add right now would get put into the queue after Sept 2018 but before anything else. It almost looks like the data is messed up where old articles had their relevant date field updated to be way in the future so they will always be first.

I'm about to actually read the stuff in my Readling List just to get the ordering sorted out again 😮

**Comment by rhymes** [comment] 2020-07-05 08:24
I wonder if the issue is data (missing the updated field as @ItsASine hinted at) or the ordering algorithm that's borked.

cc @mstruve

**Comment by mstruve** [comment] 2020-07-05 13:03
Reading list is [ordered by reaction ID](https://github.com/thepracticaldev/dev.to/blob/master/app/services/search/query_builders/reaction.rb#L24) so if you react to a 2018 article now it will appear at the top of your list. If we want to add a feature to allow sorting by other attributes for reactions then I think that would solve this issue.

**Comment by rhymes** [comment] 2020-07-06 10:20
This is the feature request to add custom sorting https://github.com/thepracticaldev/dev.to/issues/7532

**Comment by mstruve** [comment] 2020-07-06 13:08
Closing since this is expected behavior and we already have a feature to update it to something better and more flexible

**Closed by mstruve** 2020-07-06 13:08 UTC
Labels: area: reading list, type: bug
