### ISSUE TITLE
please add follow back buttons to https://dev.to/dashboard/user_followers

### ISSUE THREAD

**Issue by osde8info** [thepracticaldev/dev.to#5640] opened 2020-01-22 07:05 UTC
**Is your feature request related to a problem? Please describe.**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Describe the solution you'd like**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Describe alternatives you've considered**

none

**Additional context**

please add follow back buttons to https://dev.to/dashboard/user_followers

**Comment by rhymes** [comment] 2020-01-22 08:21
Hi @osde8info, thanks for the feature request! 

I'm going to close this as a duplicate of https://github.com/thepracticaldev/dev.to/issues/3169 which has a related PR in https://github.com/thepracticaldev/dev.to/pull/3294 but was eventually abandoned.

Anyway, the feature request is sound.

Thank you!

**Closed by rhymes** 2020-01-22 08:21 UTC
Labels: triage
